local LocalAnimationBuilder = require(script.Parent.Parent.Util.LocalAnimationBuilder)

local Enemies = {
	Goblin = {
		id = "Goblin",
		name = "Goblin",
		MaxHP = 50,
		PhysicalDamage = 8,
		PhysicalResistance = 3,
		MoveSpeed = 4,
		attackCooldown = 3,
		aggroRange = 40,
		attackRange = 6,
		xpReward = 20,
		coinReward = 20,
		dropChance = 0.35,
		dropItem = "Herb",
		lootTableId = "GoblinDrops",
		color = Color3.fromRGB(60, 140, 60),
		damageType = "physical",
		statusEffect = "Bleed",
		walkAnimKey = "GetGoblinWalk",
		idleAnimKey = "GetGoblinIdle",
		attackAnimKeys = { "GetGoblinAttack1", "GetGoblinAttack2" },
		attackHitTime = 0.4,
	},
	Skeleton = {
		id = "Skeleton",
		name = "Skeleton",
		MaxHP = 75,
		PhysicalDamage = 12,
		PhysicalResistance = 5,
		MoveSpeed = 4,
		attackCooldown = 3.5,
		aggroRange = 45,
		attackRange = 6,
		xpReward = 35,
		coinReward = 30,
		dropChance = 0.25,
		dropItem = "Herb",
		lootTableId = "SkeletonDrops",
		color = Color3.fromRGB(200, 200, 190),
		damageType = "physical",
		statusEffect = "Slow",
		walkAnimKey = "GetSkeletonWalk",
		idleAnimKey = "GetSkeletonIdle",
		attackAnimKeys = { "GetSkeletonAttack1", "GetSkeletonAttack2" },
		attackHitTime = 0.45,
	},
	Orc = {
		id = "Orc",
		name = "Orc",
		MaxHP = 120,
		PhysicalDamage = 18,
		PhysicalResistance = 8,
		MoveSpeed = 3,
		attackCooldown = 4,
		aggroRange = 40,
		attackRange = 7,
		xpReward = 60,
		coinReward = 50,
		dropChance = 0.5,
		dropItem = "IronOre",
		lootTableId = "OrcDrops",
		color = Color3.fromRGB(50, 100, 40),
		damageType = "physical",
		statusEffect = "Stun",
		walkAnimKey = "GetOrcWalk",
		idleAnimKey = "GetOrcIdle",
		attackAnimKeys = { "GetOrcAttack1", "GetOrcAttack2", "GetOrcAttack3" },
		attackHitTime = 0.5,
	},
	DireWolf = {
		id = "DireWolf",
		name = "DireWolf",
		MaxHP = 80,
		PhysicalDamage = 14,
		PhysicalResistance = 4,
		MoveSpeed = 7,
		attackCooldown = 2,
		aggroRange = 60,
		attackRange = 6,
		xpReward = 40,
		coinReward = 35,
		dropChance = 0.3,
		dropItem = "BeastHide",
		lootTableId = "WolfDrops",
		color = Color3.fromRGB(80, 80, 80),
		damageType = "physical",
		statusEffect = "Bleed",
		walkAnimKey = "GetDireWolfWalk",
		idleAnimKey = "GetDireWolfIdle",
		attackAnimKeys = { "GetDireWolfAttack1", "GetDireWolfAttack2" },
		attackHitTime = 0.3,
	},
	Spider = {
		id = "Spider",
		name = "Spider",
		MaxHP = 60,
		PhysicalDamage = 10,
		PhysicalResistance = 2,
		MoveSpeed = 6,
		attackCooldown = 2.5,
		aggroRange = 50,
		attackRange = 5,
		xpReward = 30,
		coinReward = 25,
		dropChance = 0.4,
		dropItem = "BeastHide",
		lootTableId = "SpiderDrops",
		color = Color3.fromRGB(40, 40, 40),
		damageType = "magic",
		statusEffect = "Poison",
		walkAnimKey = "GetSpiderWalk",
		idleAnimKey = "GetSpiderIdle",
		attackAnimKeys = { "GetSpiderAttack1", "GetSpiderAttack2" },
		attackHitTime = 0.35,
	},
	Slime = {
		id = "Slime",
		name = "Slime",
		MaxHP = 40,
		PhysicalDamage = 5,
		PhysicalResistance = 1,
		MoveSpeed = 2,
		attackCooldown = 4,
		aggroRange = 30,
		attackRange = 5,
		xpReward = 15,
		coinReward = 10,
		dropChance = 0.2,
		dropItem = "Herb",
		lootTableId = "SlimeDrops",
		color = Color3.fromRGB(50, 200, 100),
		damageType = "magic",
		statusEffect = "Slow",
		walkAnimKey = "GetSlimeWalk",
		idleAnimKey = "GetSlimeIdle",
		attackAnimKeys = { "GetSlimeAttack1", "GetSlimeAttack2" },
		attackHitTime = 0.5,
	},
}

function Enemies.GetAnimId(key)
	return LocalAnimationBuilder.GetAnimId(key)
end

return Enemies
