local FastTravel = {
	MapBounds = {
		minX = -1760,
		maxX = 1760,
		minZ = -1760,
		maxZ = 1760,
	},

	MiniMapBounds = {
		minX = -800,
		maxX = 800,
		minZ = -800,
		maxZ = 800,
	},

	Categories = { "All", "Gates", "Town", "Combat", "Services" },

	Locations = {
		EastGate = {
			id = "EastGate",
			displayName = "East Castle Gate",
			region = "Kingdom",
			category = "Gates",
			position = Vector3.new(700, 0, 0),
			spawnOffset = Vector3.new(-8, 0, 0),
			postOffset = Vector3.new(-28, 0, 32), -- Inside the wall, beside the north side of the road.
			icon = "rbxassetid://6031075938",
			description = "Eastern entrance of the kingdom.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "default" },
		},
		NorthGate = {
			id = "NorthGate",
			displayName = "North Castle Gate",
			region = "Kingdom",
			category = "Gates",
			position = Vector3.new(0, 0, -700),
			spawnOffset = Vector3.new(0, 0, 8),
			postOffset = Vector3.new(-32, 0, 28), -- Inside the wall, beside the west side of the road.
			icon = "rbxassetid://6031075938",
			description = "Northern entrance of the kingdom.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "default" },
		},
		WestGate = {
			id = "WestGate",
			displayName = "West Castle Gate",
			region = "Kingdom",
			category = "Gates",
			position = Vector3.new(-700, 0, 0),
			spawnOffset = Vector3.new(8, 0, 0),
			postOffset = Vector3.new(28, 0, -32), -- Inside the wall, beside the south side of the road.
			icon = "rbxassetid://6031075938",
			description = "Western entrance of the kingdom.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "default" },
		},
		SouthGate = {
			id = "SouthGate",
			displayName = "South Castle Gate",
			region = "Kingdom",
			category = "Gates",
			position = Vector3.new(0, 0, 700),
			spawnOffset = Vector3.new(0, 0, -8),
			postOffset = Vector3.new(32, 0, -28), -- Inside the wall, beside the east side of the road.
			icon = "rbxassetid://6031075938",
			description = "Southern entrance of the kingdom.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "default" },
		},
		Marketplace = {
			id = "Marketplace",
			displayName = "Marketplace",
			region = "Kingdom",
			category = "Town",
			position = Vector3.new(80, 0, 240),
			spawnOffset = Vector3.new(0, 0, 6),
			icon = "rbxassetid://6031225800",
			description = "The bustling Roman marketplace at the heart of the village.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "default" },
		},
		TrainingGrounds = {
			id = "TrainingGrounds",
			displayName = "Training Grounds",
			region = "Kingdom",
			category = "Combat",
			position = Vector3.new(-200, 0, 400),
			spawnOffset = Vector3.new(0, 0, 6),
			icon = "rbxassetid://6031097226",
			description = "Practice your combat skills against training dummies.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "visit" },
		},
		Arena = {
			id = "Arena",
			displayName = "Arena",
			region = "Kingdom",
			category = "Combat",
			position = Vector3.new(300, 0, -300),
			spawnOffset = Vector3.new(0, 0, 6),
			icon = "rbxassetid://6031094675",
			description = "Test your might against other warriors in the arena.",
			levelRequirement = 5,
			enabled = true,
			unlockRequirement = { type = "level", level = 5 },
		},
		Blacksmith = {
			id = "Blacksmith",
			displayName = "Blacksmith",
			region = "Kingdom",
			category = "Services",
			position = Vector3.new(-80, 0, 240),
			spawnOffset = Vector3.new(0, 0, 6),
			icon = "rbxassetid://6031091030",
			description = "Forge and enhance your equipment at the blacksmith.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "visit" },
		},
		GuildHall = {
			id = "GuildHall",
			displayName = "Guild Hall",
			region = "Kingdom",
			category = "Services",
			position = Vector3.new(0, 0, 150),
			spawnOffset = Vector3.new(0, 0, 6),
			icon = "rbxassetid://6031071053",
			description = "Gather with fellow adventurers at the guild hall.",
			levelRequirement = 1,
			enabled = true,
			unlockRequirement = { type = "quest", questId = "GoblinMenace", requireCompleted = true },
		},
	},
}

return FastTravel
