local Items = {
	Herb = {
		id = "Herb",
		name = "Herb",
		description = "A common herb dropped by goblins.",
		type = "material",
		category = "materials",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(80, 180, 80),
	},
	IronOre = {
		id = "IronOre",
		name = "Iron Ore",
		description = "Ore used to upgrade warrior weapons and armor.",
		type = "material",
		category = "materials",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(140, 140, 150),
	},
	BeastHide = {
		id = "BeastHide",
		name = "Beast Hide",
		description = "Hide used to upgrade archer and kavalier gear.",
		type = "material",
		category = "materials",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(120, 90, 60),
	},
	ArcaneDust = {
		id = "ArcaneDust",
		name = "Arcane Dust",
		description = "Dust used to upgrade mage and priest gear.",
		type = "material",
		category = "materials",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(100, 80, 220),
	},

	-- ENHANCEMENT SCROLLS — SHOP-ONLY. DO NOT ADD TO LOOT TABLES.
	EnhanceScroll_5 = {
		id = "EnhanceScroll_5",
		name = "Enhancement Scroll (+5)",
		description = "Attempts to enhance gear up to +5.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 5,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(180, 200, 255),
	},
	EnhanceScroll_10 = {
		id = "EnhanceScroll_10",
		name = "Enhancement Scroll (+10)",
		description = "Attempts to enhance gear up to +10.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 10,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(140, 170, 255),
	},
	EnhanceScroll_15 = {
		id = "EnhanceScroll_15",
		name = "Enhancement Scroll (+15)",
		description = "Attempts to enhance gear up to +15.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 15,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(100, 130, 255),
	},
	EnhanceScroll_20 = {
		id = "EnhanceScroll_20",
		name = "Enhancement Scroll (+20)",
		description = "Attempts to enhance gear up to +20.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 20,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(255, 200, 80),
	},
	HealthPotion = {
		id = "HealthPotion",
		name = "Health Potion",
		description = "Restores 30 HP.",
		type = "consumable",
		category = "potions",
		usable = true,
		stackable = true,
		maxStack = 20,
		healAmount = 30,
		color = Color3.fromRGB(220, 50, 80),
	},
	ManaPotion = {
		id = "ManaPotion",
		name = "Mana Potion",
		description = "Restores 30 Mana.",
		type = "consumable",
		category = "potions",
		usable = true,
		stackable = true,
		maxStack = 20,
		manaAmount = 30,
		color = Color3.fromRGB(50, 100, 220),
	},
	IronSword = {
		id = "IronSword",
		name = "Iron Sword",
		description = "A stronger blade.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		usable = false,
		stackable = false,
		damage = 25,
		statBonuses = { PhysicalDamage = 5 },
		color = Color3.fromRGB(160, 160, 180),
	},
	WoodenSword = {
		id = "WoodenSword",
		name = "Wooden Sword",
		description = "A basic training sword.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		usable = false,
		stackable = false,
		damage = 12,
		statBonuses = { PhysicalDamage = 2 },
		color = Color3.fromRGB(139, 90, 43),
	},

	WarriorSword = {
		id = "WarriorSword",
		name = "Warrior Sword",
		description = "A sturdy blade favored by warriors.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Warrior",
		damage = 15,
		statBonuses = { PhysicalDamage = 5, PhysicalResistance = 1 },
		color = Color3.fromRGB(180, 60, 60),
	},
	WarriorHelm = {
		id = "WarriorHelm",
		name = "Warrior Helm",
		description = "Iron helm of a warrior.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 3, MaxHP = 10 },
		color = Color3.fromRGB(150, 150, 160),
	},
	WarriorPlate = {
		id = "WarriorPlate",
		name = "Warrior Plate",
		description = "Heavy plate armor.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 5, MaxHP = 15 },
		color = Color3.fromRGB(120, 120, 130),
	},
	WarriorLeggings = {
		id = "WarriorLeggings",
		name = "Warrior Leggings",
		description = "Reinforced leg armor.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 2, MaxHP = 5 },
		color = Color3.fromRGB(100, 100, 110),
	},
	WarriorBoots = {
		id = "WarriorBoots",
		name = "Warrior Boots",
		description = "Steel-plated boots.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 2, MoveSpeed = 1 },
		color = Color3.fromRGB(80, 80, 90),
	},
	WarriorGauntlets = {
		id = "WarriorGauntlets",
		name = "Warrior Gauntlets",
		description = "Iron gauntlets.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Warrior",
		statBonuses = { PhysicalDamage = 2, PhysicalResistance = 1 },
		color = Color3.fromRGB(100, 100, 110),
	},

	MageStaff = {
		id = "MageStaff",
		name = "Mage Staff",
		description = "A staff channeling arcane power.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Mage",
		damage = 8,
		statBonuses = { MagicalDamage = 8 },
		color = Color3.fromRGB(80, 100, 220),
	},
	MageHood = {
		id = "MageHood",
		name = "Mage Hood",
		description = "A hood woven with arcane threads.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 2, MaxMana = 10 },
		color = Color3.fromRGB(60, 70, 160),
	},
	MageRobe = {
		id = "MageRobe",
		name = "Mage Robe",
		description = "Robes enchanted for spellcasting.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 4, MaxMana = 15 },
		color = Color3.fromRGB(70, 80, 180),
	},
	MagePants = {
		id = "MagePants",
		name = "Mage Pants",
		description = "Light cloth pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Mage",
		statBonuses = { MaxMana = 5 },
		color = Color3.fromRGB(50, 60, 140),
	},
	MageBoots = {
		id = "MageBoots",
		name = "Mage Boots",
		description = "Soft boots for a mage.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Mage",
		statBonuses = { MoveSpeed = 1, MaxMana = 5 },
		color = Color3.fromRGB(50, 50, 100),
	},
	MageGloves = {
		id = "MageGloves",
		name = "Mage Gloves",
		description = "Gloves that enhance spell focus.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 3 },
		color = Color3.fromRGB(60, 70, 150),
	},

	ArcherBow = {
		id = "ArcherBow",
		name = "Hunter Bow",
		description = "A reliable bow for ranged combat.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Archer",
		damage = 12,
		statBonuses = { PhysicalDamage = 4 },
		color = Color3.fromRGB(60, 160, 80),
	},
	ArcherCap = {
		id = "ArcherCap",
		name = "Archer Cap",
		description = "A light leather cap.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Archer",
		statBonuses = { PhysicalDamage = 1, MoveSpeed = 1 },
		color = Color3.fromRGB(80, 120, 60),
	},
	ArcherVest = {
		id = "ArcherVest",
		name = "Archer Vest",
		description = "Leather vest for mobility.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Archer",
		statBonuses = { PhysicalResistance = 2, MoveSpeed = 1 },
		color = Color3.fromRGB(70, 110, 50),
	},
	ArcherPants = {
		id = "ArcherPants",
		name = "Archer Pants",
		description = "Flexible hunting pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Archer",
		statBonuses = { MoveSpeed = 1 },
		color = Color3.fromRGB(60, 90, 45),
	},
	ArcherBoots = {
		id = "ArcherBoots",
		name = "Archer Boots",
		description = "Light boots for swift movement.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Archer",
		statBonuses = { MoveSpeed = 2 },
		color = Color3.fromRGB(50, 80, 40),
	},
	ArcherGloves = {
		id = "ArcherGloves",
		name = "Archer Gloves",
		description = "Gloves that improve grip on the bowstring.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Archer",
		statBonuses = { PhysicalDamage = 2 },
		color = Color3.fromRGB(70, 100, 50),
	},

	PriestMace = {
		id = "PriestMace",
		name = "Holy Mace",
		description = "A mace blessed with holy light.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Priest",
		damage = 10,
		statBonuses = { MagicalDamage = 4 },
		color = Color3.fromRGB(220, 200, 80),
	},
	PriestHood = {
		id = "PriestHood",
		name = "Priest Hood",
		description = "White hood of the clergy.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 2, MaxMana = 8 },
		color = Color3.fromRGB(240, 240, 220),
	},
	PriestRobe = {
		id = "PriestRobe",
		name = "Priest Robe",
		description = "Sacred robes of healing.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 3, MaxMana = 12, MaxHP = 5 },
		color = Color3.fromRGB(220, 220, 200),
	},
	PriestPants = {
		id = "PriestPants",
		name = "Priest Pants",
		description = "Simple cloth pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Priest",
		statBonuses = { MaxMana = 5 },
		color = Color3.fromRGB(200, 200, 180),
	},
	PriestBoots = {
		id = "PriestBoots",
		name = "Priest Boots",
		description = "Comfortable walking boots.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Priest",
		statBonuses = { MaxMana = 3 },
		color = Color3.fromRGB(180, 180, 160),
	},
	PriestGloves = {
		id = "PriestGloves",
		name = "Priest Gloves",
		description = "Gloves that channel healing energy.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 2, MaxMana = 5 },
		color = Color3.fromRGB(210, 210, 190),
	},

	KavalierSpear = {
		id = "KavalierSpear",
		name = "Kavalier Spear",
		description = "A long spear for lancer combat.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Kavalier",
		damage = 14,
		statBonuses = { PhysicalDamage = 5 },
		color = Color3.fromRGB(140, 80, 200),
		animations = {
			attack = {
				"rbxassetid://10468688463",
				"rbxassetid://10468688204"
			}
		},
	},
	KavalierHelm = {
		id = "KavalierHelm",
		name = "Kavalier Helm",
		description = "Ornate lancer helm.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 2, PhysicalDamage = 1 },
		color = Color3.fromRGB(130, 70, 180),
	},
	KavalierArmor = {
		id = "KavalierArmor",
		name = "Kavalier Armor",
		description = "Medium armor for mounted combat.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 4, MaxHP = 10 },
		color = Color3.fromRGB(110, 60, 160),
	},
	KavalierPants = {
		id = "KavalierPants",
		name = "Kavalier Pants",
		description = "Reinforced riding pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 2, MoveSpeed = 1 },
		color = Color3.fromRGB(100, 55, 150),
	},
	KavalierBoots = {
		id = "KavalierBoots",
		name = "Kavalier Boots",
		description = "Boots built for charging.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Kavalier",
		statBonuses = { MoveSpeed = 2 },
		color = Color3.fromRGB(90, 50, 140),
	},
	KavalierGauntlets = {
		id = "KavalierGauntlets",
		name = "Kavalier Gauntlets",
		description = "Gauntlets for a firm spear grip.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalDamage = 2 },
		color = Color3.fromRGB(120, 65, 170),
	},
}

return Items
