-- weaponSkin: style = grip/visual profile (sword|staff|bow|mace|spear), toolHold = class hold anim
local Items = {
	Herb = {
		id = "Herb",
		name = "Herb",
		description = "A common herb dropped by goblins.",
		type = "material",
		category = "materials",
		rarity = "Common",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(80, 180, 80),
	},
	IronOre = {
		id = "IronOre",
		name = "Iron Ore",
		description = "Ore used to upgrade warrior weapons and armor.",
		type = "material",
		category = "materials",
		rarity = "Common",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(140, 140, 150),
	},
	BeastHide = {
		id = "BeastHide",
		name = "Beast Hide",
		description = "Hide used to upgrade archer and kavalier gear.",
		type = "material",
		category = "materials",
		rarity = "Common",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(120, 90, 60),
	},
	ArcaneDust = {
		id = "ArcaneDust",
		name = "Arcane Dust",
		description = "Dust used to upgrade mage and priest gear.",
		type = "material",
		category = "materials",
		rarity = "Common",
		usable = false,
		stackable = true,
		maxStack = 99,
		supportsRarity = true,
		color = Color3.fromRGB(100, 80, 220),
	},

	-- ENHANCEMENT SCROLLS — SHOP-ONLY. DO NOT ADD TO LOOT TABLES.
	EnhanceScroll_5 = {
		id = "EnhanceScroll_5",
		name = "Enhancement Scroll (+5)",
		description = "Attempts to enhance gear up to +5.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 5,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(180, 200, 255),
	},
	EnhanceScroll_10 = {
		id = "EnhanceScroll_10",
		name = "Enhancement Scroll (+10)",
		description = "Attempts to enhance gear up to +10.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 10,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(140, 170, 255),
	},
	EnhanceScroll_15 = {
		id = "EnhanceScroll_15",
		name = "Enhancement Scroll (+15)",
		description = "Attempts to enhance gear up to +15.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 15,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(100, 130, 255),
	},
	EnhanceScroll_20 = {
		id = "EnhanceScroll_20",
		name = "Enhancement Scroll (+20)",
		description = "Attempts to enhance gear up to +20.",
		type = "scroll",
		category = "scrolls",
		scrollTier = 20,
		usable = false,
		stackable = true,
		maxStack = 20,
		color = Color3.fromRGB(255, 200, 80),
	},
	HealthPotion = {
		id = "HealthPotion",
		name = "Health Potion",
		description = "Restores 30 HP.",
		type = "consumable",
		category = "potions",
		rarity = "Common",
		usable = true,
		stackable = true,
		maxStack = 20,
		healAmount = 30,
		color = Color3.fromRGB(220, 50, 80),
	},
	ManaPotion = {
		id = "ManaPotion",
		name = "Mana Potion",
		description = "Restores 30 Mana.",
		type = "consumable",
		category = "potions",
		rarity = "Common",
		usable = true,
		stackable = true,
		maxStack = 20,
		manaAmount = 30,
		color = Color3.fromRGB(50, 100, 220),
	},
	IronSword = {
		id = "IronSword",
		name = "Iron Sword",
		description = "A stronger blade.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		rarity = "Common",
		usable = false,
		stackable = false,
		damage = 25,
		statBonuses = { PhysicalDamage = 5 },
		color = Color3.fromRGB(160, 160, 180),
		weaponSkin = { style = "sword", toolHold = "Warrior" },
	},
	WoodenSword = {
		id = "WoodenSword",
		name = "Wooden Sword",
		description = "A basic training sword.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		rarity = "Common",
		usable = false,
		stackable = false,
		damage = 12,
		statBonuses = { PhysicalDamage = 2 },
		color = Color3.fromRGB(139, 90, 43),
		weaponSkin = { style = "sword", toolHold = "Warrior" },
	},

	WarriorSword = {
		id = "WarriorSword",
		name = "Warrior Sword",
		description = "A sturdy blade favored by warriors.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		rarity = "Uncommon",
		classRestriction = "Warrior",
		damage = 15,
		statBonuses = { PhysicalDamage = 5, PhysicalResistance = 1 },
		color = Color3.fromRGB(180, 60, 60),
		weaponSkin = { style = "sword", toolHold = "Warrior" },
	},
	WarriorHelm = {
		id = "WarriorHelm",
		name = "Warrior Helm",
		description = "Iron helm of a warrior.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 3, MaxHP = 10 },
		color = Color3.fromRGB(150, 150, 160),
	},
	WarriorPlate = {
		id = "WarriorPlate",
		name = "Warrior Plate",
		description = "Heavy plate armor.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 5, MaxHP = 15 },
		color = Color3.fromRGB(120, 120, 130),
	},
	WarriorLeggings = {
		id = "WarriorLeggings",
		name = "Warrior Leggings",
		description = "Reinforced leg armor.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 2, MaxHP = 5 },
		color = Color3.fromRGB(100, 100, 110),
	},
	WarriorBoots = {
		id = "WarriorBoots",
		name = "Warrior Boots",
		description = "Steel-plated boots.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 2, MoveSpeed = 1 },
		color = Color3.fromRGB(80, 80, 90),
	},
	WarriorGauntlets = {
		id = "WarriorGauntlets",
		name = "Warrior Gauntlets",
		description = "Iron gauntlets.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Warrior",
		statBonuses = { PhysicalDamage = 2, PhysicalResistance = 1 },
		color = Color3.fromRGB(100, 100, 110),
	},
	WarriorShoulders = {
		id = "WarriorShoulders",
		name = "Warrior Pauldrons",
		description = "Steel shoulder guards.",
		type = "shoulders",
		category = "armor",
		slot = "shoulders",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 2, MaxHP = 8 },
		color = Color3.fromRGB(135, 135, 145),
	},
	WarriorUpperArms = {
		id = "WarriorUpperArms",
		name = "Warrior Arm Guards",
		description = "Plate covering the upper arms.",
		type = "upperArms",
		category = "armor",
		slot = "upperArms",
		classRestriction = "Warrior",
		statBonuses = { PhysicalResistance = 3, MaxHP = 5 },
		color = Color3.fromRGB(110, 110, 120),
	},

	MageStaff = {
		id = "MageStaff",
		name = "Mage Staff",
		description = "A staff channeling arcane power.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Mage",
		damage = 8,
		statBonuses = { MagicalDamage = 8 },
		color = Color3.fromRGB(80, 100, 220),
		weaponSkin = { style = "staff", toolHold = "Mage" },
	},
	MageHood = {
		id = "MageHood",
		name = "Mage Hood",
		description = "A hood woven with arcane threads.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 2, MaxMana = 10 },
		color = Color3.fromRGB(60, 70, 160),
	},
	MageRobe = {
		id = "MageRobe",
		name = "Mage Robe",
		description = "Robes enchanted for spellcasting.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 4, MaxMana = 15 },
		color = Color3.fromRGB(70, 80, 180),
	},
	MagePants = {
		id = "MagePants",
		name = "Mage Pants",
		description = "Light cloth pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Mage",
		statBonuses = { MaxMana = 5 },
		color = Color3.fromRGB(50, 60, 140),
	},
	MageBoots = {
		id = "MageBoots",
		name = "Mage Boots",
		description = "Soft boots for a mage.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Mage",
		statBonuses = { MoveSpeed = 1, MaxMana = 5 },
		color = Color3.fromRGB(50, 50, 100),
	},
	MageGloves = {
		id = "MageGloves",
		name = "Mage Gloves",
		description = "Gloves that enhance spell focus.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 3 },
		color = Color3.fromRGB(60, 70, 150),
	},
	MageShoulders = {
		id = "MageShoulders",
		name = "Mage Mantle",
		description = "Arcane shoulder mantle.",
		type = "shoulders",
		category = "armor",
		slot = "shoulders",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 1, MaxMana = 8 },
		color = Color3.fromRGB(65, 75, 170),
	},
	MageUpperArms = {
		id = "MageUpperArms",
		name = "Mage Arm Wraps",
		description = "Enchanted wraps for the upper arms.",
		type = "upperArms",
		category = "armor",
		slot = "upperArms",
		classRestriction = "Mage",
		statBonuses = { MagicalDamage = 2, MaxMana = 5 },
		color = Color3.fromRGB(65, 75, 165),
	},

	ArcherBow = {
		id = "ArcherBow",
		name = "Hunter Bow",
		description = "A reliable bow for ranged combat.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Archer",
		damage = 12,
		statBonuses = { PhysicalDamage = 4 },
		color = Color3.fromRGB(60, 160, 80),
		weaponSkin = { style = "bow", toolHold = "Archer" },
	},
	ArcherCap = {
		id = "ArcherCap",
		name = "Archer Cap",
		description = "A light leather cap.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Archer",
		statBonuses = { PhysicalDamage = 1, MoveSpeed = 1 },
		color = Color3.fromRGB(80, 120, 60),
	},
	ArcherVest = {
		id = "ArcherVest",
		name = "Archer Vest",
		description = "Leather vest for mobility.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Archer",
		statBonuses = { PhysicalResistance = 2, MoveSpeed = 1 },
		color = Color3.fromRGB(70, 110, 50),
	},
	ArcherPants = {
		id = "ArcherPants",
		name = "Archer Pants",
		description = "Flexible hunting pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Archer",
		statBonuses = { MoveSpeed = 1 },
		color = Color3.fromRGB(60, 90, 45),
	},
	ArcherBoots = {
		id = "ArcherBoots",
		name = "Archer Boots",
		description = "Light boots for swift movement.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Archer",
		statBonuses = { MoveSpeed = 2 },
		color = Color3.fromRGB(50, 80, 40),
	},
	ArcherGloves = {
		id = "ArcherGloves",
		name = "Archer Gloves",
		description = "Gloves that improve grip on the bowstring.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Archer",
		statBonuses = { PhysicalDamage = 2 },
		color = Color3.fromRGB(70, 100, 50),
	},
	ArcherShoulders = {
		id = "ArcherShoulders",
		name = "Archer Shoulder Guards",
		description = "Light leather shoulder guards.",
		type = "shoulders",
		category = "armor",
		slot = "shoulders",
		classRestriction = "Archer",
		statBonuses = { PhysicalDamage = 1, MoveSpeed = 1 },
		color = Color3.fromRGB(75, 115, 55),
	},
	ArcherUpperArms = {
		id = "ArcherUpperArms",
		name = "Archer Arm Bracers",
		description = "Bracers protecting the upper arms.",
		type = "upperArms",
		category = "armor",
		slot = "upperArms",
		classRestriction = "Archer",
		statBonuses = { PhysicalResistance = 1, MoveSpeed = 1 },
		color = Color3.fromRGB(65, 100, 48),
	},

	PriestMace = {
		id = "PriestMace",
		name = "Holy Mace",
		description = "A mace blessed with holy light.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Priest",
		damage = 10,
		statBonuses = { MagicalDamage = 4 },
		color = Color3.fromRGB(220, 200, 80),
		weaponSkin = { style = "mace", toolHold = "Priest" },
	},
	PriestHood = {
		id = "PriestHood",
		name = "Priest Hood",
		description = "White hood of the clergy.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 2, MaxMana = 8 },
		color = Color3.fromRGB(240, 240, 220),
	},
	PriestRobe = {
		id = "PriestRobe",
		name = "Priest Robe",
		description = "Sacred robes of healing.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 3, MaxMana = 12, MaxHP = 5 },
		color = Color3.fromRGB(220, 220, 200),
	},
	PriestPants = {
		id = "PriestPants",
		name = "Priest Pants",
		description = "Simple cloth pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Priest",
		statBonuses = { MaxMana = 5 },
		color = Color3.fromRGB(200, 200, 180),
	},
	PriestBoots = {
		id = "PriestBoots",
		name = "Priest Boots",
		description = "Comfortable walking boots.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Priest",
		statBonuses = { MaxMana = 3 },
		color = Color3.fromRGB(180, 180, 160),
	},
	PriestGloves = {
		id = "PriestGloves",
		name = "Priest Gloves",
		description = "Gloves that channel healing energy.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 2, MaxMana = 5 },
		color = Color3.fromRGB(210, 210, 190),
	},
	PriestShoulders = {
		id = "PriestShoulders",
		name = "Priest Mantle",
		description = "Holy shoulder mantle.",
		type = "shoulders",
		category = "armor",
		slot = "shoulders",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 1, MaxHP = 5 },
		color = Color3.fromRGB(230, 230, 210),
	},
	PriestUpperArms = {
		id = "PriestUpperArms",
		name = "Priest Arm Wraps",
		description = "Blessed wraps for the upper arms.",
		type = "upperArms",
		category = "armor",
		slot = "upperArms",
		classRestriction = "Priest",
		statBonuses = { MagicalDamage = 2, MaxHP = 3 },
		color = Color3.fromRGB(215, 215, 195),
	},

	KavalierSpear = {
		id = "KavalierSpear",
		name = "Kavalier Spear",
		description = "A long spear for lancer combat.",
		type = "weapon",
		category = "weapons",
		slot = "weapon",
		classRestriction = "Kavalier",
		damage = 14,
		statBonuses = { PhysicalDamage = 5 },
		color = Color3.fromRGB(140, 80, 200),
		weaponSkin = { style = "spear", toolHold = "Kavalier" },
	},
	KavalierHelm = {
		id = "KavalierHelm",
		name = "Kavalier Helm",
		description = "Ornate lancer helm.",
		type = "helmet",
		category = "armor",
		slot = "helmet",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 2, PhysicalDamage = 1 },
		color = Color3.fromRGB(130, 70, 180),
	},
	KavalierArmor = {
		id = "KavalierArmor",
		name = "Kavalier Armor",
		description = "Medium armor for mounted combat.",
		type = "armor",
		category = "armor",
		slot = "armor",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 4, MaxHP = 10 },
		color = Color3.fromRGB(110, 60, 160),
	},
	KavalierPants = {
		id = "KavalierPants",
		name = "Kavalier Pants",
		description = "Reinforced riding pants.",
		type = "pants",
		category = "armor",
		slot = "pants",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 2, MoveSpeed = 1 },
		color = Color3.fromRGB(100, 55, 150),
	},
	KavalierBoots = {
		id = "KavalierBoots",
		name = "Kavalier Boots",
		description = "Boots built for charging.",
		type = "boots",
		category = "armor",
		slot = "boots",
		classRestriction = "Kavalier",
		statBonuses = { MoveSpeed = 2 },
		color = Color3.fromRGB(90, 50, 140),
	},
	KavalierGauntlets = {
		id = "KavalierGauntlets",
		name = "Kavalier Gauntlets",
		description = "Gauntlets for a firm spear grip.",
		type = "gloves",
		category = "armor",
		slot = "gloves",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalDamage = 2 },
		color = Color3.fromRGB(120, 65, 170),
	},
	KavalierShoulders = {
		id = "KavalierShoulders",
		name = "Kavalier Pauldrons",
		description = "Ornate lancer pauldrons.",
		type = "shoulders",
		category = "armor",
		slot = "shoulders",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 2, MaxHP = 6 },
		color = Color3.fromRGB(150, 85, 200),
	},
	KavalierUpperArms = {
		id = "KavalierUpperArms",
		name = "Kavalier Arm Guards",
		description = "Arm guards for a lancer's charge.",
		type = "upperArms",
		category = "armor",
		slot = "upperArms",
		classRestriction = "Kavalier",
		statBonuses = { PhysicalResistance = 2, PhysicalDamage = 1 },
		color = Color3.fromRGB(130, 75, 185),
	},

	-- ==========================================
	-- HIGH-TIER / MYTHIC EQUIPMENT
	-- ==========================================
	IronBroadsword = { id = "IronBroadsword", name = "Iron Broadsword", description = "High physical attack sword.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Warrior", damage = 35, statBonuses = { PhysicalDamage = 35 }, color = Color3.fromRGB(160, 160, 160), weaponSkin = { style = "sword", toolHold = "Warrior" } },
	KnightsHonor = { id = "KnightsHonor", name = "Knight's Honor", description = "A gleaming epic sword.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Warrior", damage = 70, statBonuses = { PhysicalDamage = 70, PhysicalResistance = 10 }, color = Color3.fromRGB(150, 50, 200), weaponSkin = { style = "sword", toolHold = "Warrior" } },
	AegisPlate = { id = "AegisPlate", name = "Aegis Plate", description = "Mythic armor forged from the stars.", type = "armor", category = "armor", slot = "armor", classRestriction = "Warrior", statBonuses = { PhysicalResistance = 150, MagicResistance = 50, MaxHP = 200 }, color = Color3.fromRGB(255, 50, 50) },
	CrystalStaff = { id = "CrystalStaff", name = "Crystal Staff", description = "High magic attack staff.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Mage", damage = 15, statBonuses = { MagicalDamage = 45 }, color = Color3.fromRGB(100, 200, 255), weaponSkin = { style = "staff", toolHold = "Mage" } },
	Starcaller = { id = "Starcaller", name = "Starcaller", description = "Massive magic attack staff.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Mage", damage = 30, statBonuses = { MagicalDamage = 100 }, color = Color3.fromRGB(255, 180, 50), weaponSkin = { style = "staff", toolHold = "Mage" } },
	CrownOfTheArchmage = { id = "CrownOfTheArchmage", name = "Crown of the Archmage", description = "Mythic crown for ultimate spellcasting.", type = "helmet", category = "armor", slot = "helmet", classRestriction = "Mage", statBonuses = { MaxMana = 200, MagicResistance = 50 }, color = Color3.fromRGB(255, 50, 50) },
	HuntersLongbow = { id = "HuntersLongbow", name = "Hunter's Longbow", description = "Slower, harder hitting bow.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Archer", damage = 35, statBonuses = { PhysicalDamage = 35 }, color = Color3.fromRGB(80, 140, 70), weaponSkin = { style = "bow", toolHold = "Archer" } },
	Windpiercer = { id = "Windpiercer", name = "Windpiercer", description = "Epic fast firing bow.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Archer", damage = 65, statBonuses = { PhysicalDamage = 65 }, color = Color3.fromRGB(150, 50, 200), weaponSkin = { style = "bow", toolHold = "Archer" } },
	QuiverOfTheCosmos = { id = "QuiverOfTheCosmos", name = "Quiver of the Cosmos", description = "Mythic quiver granting massive speed.", type = "shoulders", category = "armor", slot = "shoulders", classRestriction = "Archer", statBonuses = { Evasion = 15 }, color = Color3.fromRGB(255, 50, 50) },
	HolyRod = { id = "HolyRod", name = "Holy Rod", description = "Boosts healing spells.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Priest", damage = 15, statBonuses = { MagicalDamage = 25 }, color = Color3.fromRGB(230, 210, 100), weaponSkin = { style = "mace", toolHold = "Priest" } },
	SunBringer = { id = "SunBringer", name = "Sun Bringer", description = "Epic healing mace.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Priest", damage = 30, statBonuses = { MagicalDamage = 60 }, color = Color3.fromRGB(150, 50, 200), weaponSkin = { style = "mace", toolHold = "Priest" } },
	HeartOfTheSeraph = { id = "HeartOfTheSeraph", name = "Heart of the Seraph", description = "Mythic robes of the divine.", type = "armor", category = "armor", slot = "armor", classRestriction = "Priest", statBonuses = { MaxHP = 150, MagicResistance = 100 }, color = Color3.fromRGB(255, 50, 50) },
	SilverHalberd = { id = "SilverHalberd", name = "Silver Halberd", description = "Sweeping attack spear.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Kavalier", damage = 38, statBonuses = { PhysicalDamage = 38 }, color = Color3.fromRGB(180, 180, 200), weaponSkin = { style = "spear", toolHold = "Kavalier" } },
	DragonLance = { id = "DragonLance", name = "Dragon Lance", description = "Massive damage legendary lance.", type = "weapon", category = "weapons", slot = "weapon", classRestriction = "Kavalier", damage = 110, statBonuses = { PhysicalDamage = 110 }, color = Color3.fromRGB(255, 180, 50), weaponSkin = { style = "spear", toolHold = "Kavalier" } },
	MeteorStrideSabatons = { id = "MeteorStrideSabatons", name = "Meteor Stride Sabatons", description = "Mythic boots for charging.", type = "boots", category = "armor", slot = "boots", classRestriction = "Kavalier", statBonuses = { MoveSpeed = 5, PhysicalResistance = 50, Evasion = 10 }, color = Color3.fromRGB(255, 50, 50) },

	-- ==========================================
	-- MATERIALS (From Plan)
	-- ==========================================
	SlimeGel = { id = "SlimeGel", name = "Slime Gel", description = "Basic potion material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(100, 255, 100) },
	BatWing = { id = "BatWing", name = "Bat Wing", description = "Swiftness material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(80, 80, 80) },
	GoblinCloth = { id = "GoblinCloth", name = "Goblin Cloth", description = "Early armor material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(120, 100, 80) },
	WolfFang = { id = "WolfFang", name = "Wolf Fang", description = "Early weapon material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 200, 200) },
	MagicCore = { id = "MagicCore", name = "Magic Core", description = "Basic wand material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(100, 150, 255) },
	SpiderSilk = { id = "SpiderSilk", name = "Spider Silk", description = "Robe material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(230, 230, 230) },
	BearClaw = { id = "BearClaw", name = "Bear Claw", description = "Warrior weapon material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(130, 100, 60) },
	DrakeScale = { id = "DrakeScale", name = "Drake Scale", description = "High-tier armor material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 80, 80) },
	PhoenixFeather = { id = "PhoenixFeather", name = "Phoenix Feather", description = "Ultimate wand material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 120, 50) },
	DragonHorn = { id = "DragonHorn", name = "Dragon Horn", description = "Ultimate weapon material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(250, 200, 100) },
	LeviathanEye = { id = "LeviathanEye", name = "Leviathan Eye", description = "Mythic artifact material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(50, 50, 255) },
	CopperOre = { id = "CopperOre", name = "Copper Ore", description = "Basic metal ore.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(184, 115, 51) },
	SilverOre = { id = "SilverOre", name = "Silver Ore", description = "Uncommon ore.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(192, 192, 192) },
	GoldOre = { id = "GoldOre", name = "Gold Ore", description = "Rare ore.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 215, 0) },
	CrystalShard = { id = "CrystalShard", name = "Crystal Shard", description = "Magic ore.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(150, 200, 255) },
	Ruby = { id = "Ruby", name = "Ruby", description = "Fire gem.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(220, 20, 60) },
	Sapphire = { id = "Sapphire", name = "Sapphire", description = "Water gem.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(15, 82, 186) },
	Emerald = { id = "Emerald", name = "Emerald", description = "Nature gem.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(80, 200, 120) },
	Diamond = { id = "Diamond", name = "Diamond", description = "Endgame gem.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(185, 242, 255) },
	StarFragment = { id = "StarFragment", name = "Star Fragment", description = "Legendary gem.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 255, 100) },
	PrismaticGeode = { id = "PrismaticGeode", name = "Prismatic Geode", description = "Mythic forging gem.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 100, 255) },
	SweetLeaf = { id = "SweetLeaf", name = "Sweet Leaf", description = "Basic healing material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(120, 200, 120) },
	HealingBlossom = { id = "HealingBlossom", name = "Healing Blossom", description = "Basic healing material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 100, 150) },
	ManaRoot = { id = "ManaRoot", name = "Mana Root", description = "Mana material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(100, 100, 200) },
	SwiftStem = { id = "SwiftStem", name = "Swift Stem", description = "Haste material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 200, 100) },
	IronbarkWood = { id = "IronbarkWood", name = "Ironbark Wood", description = "Tough wood.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(139, 100, 50) },
	Glowcap = { id = "Glowcap", name = "Glowcap", description = "Glowing mushroom.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(100, 255, 200) },
	SunPetal = { id = "SunPetal", name = "Sun Petal", description = "Holy plant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 255, 150) },
	MoonFlower = { id = "MoonFlower", name = "Moon Flower", description = "Arcane plant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(150, 150, 255) },
	LifeSeed = { id = "LifeSeed", name = "Life Seed", description = "Elixir material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(50, 255, 100) },
	YggdrasilLeaf = { id = "YggdrasilLeaf", name = "Yggdrasil Leaf", description = "Legendary plant.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 255, 50) },
	WorldTreeSap = { id = "WorldTreeSap", name = "World Tree Sap", description = "Mythic plant essence.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 255, 255) },
	SparkDust = { id = "SparkDust", name = "Spark Dust", description = "Basic enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 200, 250) },
	WaterDrop = { id = "WaterDrop", name = "Water Drop", description = "Basic enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(100, 150, 255) },
	WindWhisper = { id = "WindWhisper", name = "Wind Whisper", description = "Speed enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 255, 255) },
	EarthShard = { id = "EarthShard", name = "Earth Shard", description = "Defense enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(150, 100, 50) },
	FireEmber = { id = "FireEmber", name = "Fire Ember", description = "Damage enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 100, 50) },
	FrostCrystal = { id = "FrostCrystal", name = "Frost Crystal", description = "Chill enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(150, 200, 255) },
	ThunderSpark = { id = "ThunderSpark", name = "Thunder Spark", description = "Haste enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 255, 100) },
	LightEssence = { id = "LightEssence", name = "Light Essence", description = "Holy enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 255, 200) },
	ShadowMote = { id = "ShadowMote", name = "Shadow Mote", description = "Sneak enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(100, 50, 150) },
	PureAether = { id = "PureAether", name = "Pure Aether", description = "Legendary enchant core.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(250, 250, 250) },
	CosmicSpark = { id = "CosmicSpark", name = "Cosmic Spark", description = "Mythic enchant material.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 100, 255) },
	RustedCoin = { id = "RustedCoin", name = "Rusted Coin", description = "Sells for a little gold.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(180, 150, 100) },
	GlassBead = { id = "GlassBead", name = "Glass Bead", description = "Early accessory part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 200, 200) },
	PolishedShell = { id = "PolishedShell", name = "Polished Shell", description = "Uncommon accessory part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(220, 200, 180) },
	ShinyPearl = { id = "ShinyPearl", name = "Shiny Pearl", description = "Magic boost part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(250, 250, 250) },
	SilverChalice = { id = "SilverChalice", name = "Silver Chalice", description = "High-value sellable.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(210, 210, 220) },
	GoldenIdol = { id = "GoldenIdol", name = "Golden Idol", description = "Epic crafting part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 215, 0) },
	JeweledCrown = { id = "JeweledCrown", name = "Jeweled Crown", description = "Legendary crafting part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 200, 100) },
	AncientRelic = { id = "AncientRelic", name = "Ancient Relic", description = "Secret weapon quest part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(150, 150, 150) },
	RoyalSeal = { id = "RoyalSeal", name = "Royal Seal", description = "Legendary gear part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(200, 50, 50) },
	DragonTear = { id = "DragonTear", name = "Dragon Tear", description = "Ultimate elixir part.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(100, 150, 255) },
	CrownOfAncients = { id = "CrownOfAncients", name = "Crown of Ancients", description = "Mythic crafting catalyst.", type = "material", category = "materials", usable = false, stackable = true, maxStack = 99, color = Color3.fromRGB(255, 50, 100) },

	-- ==========================================
	-- CONSUMABLES (From Plan)
	-- ==========================================
	AppleJuice = { id = "AppleJuice", name = "Apple Juice", description = "Heals 50 HP.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, healAmount = 50, color = Color3.fromRGB(200, 100, 50) },
	HoneyDrop = { id = "HoneyDrop", name = "Honey Drop", description = "Grants minor Regen.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, effect = "Regen", color = Color3.fromRGB(220, 180, 50) },
	RedPotion = { id = "RedPotion", name = "Red Potion", description = "Heals 150 HP.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, healAmount = 150, color = Color3.fromRGB(220, 50, 50) },
	BluePotion = { id = "BluePotion", name = "Blue Potion", description = "Restores 100 Mana.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, manaAmount = 100, color = Color3.fromRGB(50, 50, 220) },
	SpeedyBootsPotion = { id = "SpeedyBootsPotion", name = "Speedy Potion", description = "Grants Haste (+30% Move Speed).", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, effect = "Haste", color = Color3.fromRGB(150, 255, 150) },
	HardCandy = { id = "HardCandy", name = "Hard Candy", description = "+20% Physical Resistance.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, effect = "DefenseBuff", color = Color3.fromRGB(200, 150, 200) },
	MagicCookie = { id = "MagicCookie", name = "Magic Cookie", description = "+20% Magic Damage.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, effect = "MagicBuff", color = Color3.fromRGB(150, 100, 250) },
	WarmSoup = { id = "WarmSoup", name = "Warm Soup", description = "Cleanses Chill. Heals 50 HP.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, healAmount = 50, effect = "CleanseChill", color = Color3.fromRGB(250, 200, 100) },
	AntidoteHerb = { id = "AntidoteHerb", name = "Antidote Herb", description = "Cleanses Poison/Slimed.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, effect = "CleansePoison", color = Color3.fromRGB(100, 250, 100) },
	StarFruit = { id = "StarFruit", name = "Star Fruit", description = "Heals 200 HP, 100 Mana.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 20, healAmount = 200, manaAmount = 100, color = Color3.fromRGB(255, 255, 100) },
	HerosFeast = { id = "HerosFeast", name = "Hero's Feast", description = "Regen & Damage for Party.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 5, effect = "PartyBuff", color = Color3.fromRGB(255, 150, 50) },
	InvincibilityStar = { id = "InvincibilityStar", name = "Invincibility Star", description = "Grants Shield (Blocks 500 Dmg).", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 5, effect = "Shield", color = Color3.fromRGB(255, 255, 50) },
	GoldenApple = { id = "GoldenApple", name = "Golden Apple", description = "Heals 100% HP.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 5, healAmount = 9999, color = Color3.fromRGB(255, 215, 0) },
	ElixirOfLife = { id = "ElixirOfLife", name = "Elixir of Life", description = "Revives a fallen friend.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 5, effect = "Revive", color = Color3.fromRGB(150, 255, 255) },
	ScrollOfFire = { id = "ScrollOfFire", name = "Scroll of Fire", description = "Shoots a fireball.", type = "scroll", category = "scrolls", usable = true, stackable = true, maxStack = 10, effect = "Fireball", color = Color3.fromRGB(255, 100, 50) },
	ScrollOfWind = { id = "ScrollOfWind", name = "Scroll of Wind", description = "Pushes enemies & Haste.", type = "scroll", category = "scrolls", usable = true, stackable = true, maxStack = 10, effect = "WindPush", color = Color3.fromRGB(150, 255, 200) },
	ScrollOfShielding = { id = "ScrollOfShielding", name = "Scroll of Shielding", description = "Casts a small Shield.", type = "scroll", category = "scrolls", usable = true, stackable = true, maxStack = 10, effect = "SmallShield", color = Color3.fromRGB(100, 150, 255) },
	PowerCrystal = { id = "PowerCrystal", name = "Power Crystal", description = "+30% Physical Damage.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 10, effect = "AttackBuff", color = Color3.fromRGB(255, 50, 50) },
	WardingCharm = { id = "WardingCharm", name = "Warding Charm", description = "Immune to status effects.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 10, effect = "Immunity", color = Color3.fromRGB(200, 200, 255) },
	FairyDust = { id = "FairyDust", name = "Fairy Dust", description = "Cleanses Party + Regen.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 5, effect = "PartyCleanse", color = Color3.fromRGB(255, 150, 255) },
	TearsOfTheGoddess = { id = "TearsOfTheGoddess", name = "Tears of the Goddess", description = "Revives all, full heals Party.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 3, effect = "MassRevive", color = Color3.fromRGB(150, 200, 255) },
	DragonsBreathBrew = { id = "DragonsBreathBrew", name = "Dragon's Breath Brew", description = "Massive AoE blast.", type = "consumable", category = "potions", usable = true, stackable = true, maxStack = 3, effect = "MassiveAoE", color = Color3.fromRGB(255, 50, 50) },
}

local EquipmentSlots = require(script.Parent.EquipmentSlots)
local EnhancementConfig = require(script.Parent.EnhancementConfig)

-- Every player/enhancement level has a focused shop-only scroll. They are generated
-- here so the item catalog and shop cannot drift out of sync.
local scrollColors = {
	Fighter = Color3.fromRGB(210, 95, 75), Mage = Color3.fromRGB(100, 130, 255),
	Healer = Color3.fromRGB(100, 220, 160), Lucky = Color3.fromRGB(245, 200, 75),
	Guardian = Color3.fromRGB(130, 185, 205),
	Rogue = Color3.fromRGB(155, 95, 210), Hybrid = Color3.fromRGB(220, 130, 175),
}
for category, profile in pairs(EnhancementConfig.ScrollCategories) do
	for level = 1, EnhancementConfig.MAX_ENHANCE_LEVEL do
		local id = string.format("EnhanceScroll_%s_%d", category, level)
		local scaledBonuses = EnhancementConfig.GetScrollBonuses(category, level)
		Items[id] = {
			id = id,
			name = string.format("%s Enhancement Scroll (Lv. %d)", profile.label, level),
			description = string.format("Requires player level %d. Enhances gear from +%d to +%d. %s", level, level - 1, level, profile.description),
			type = "scroll", category = "scrolls", enhancementCategory = category,
			enhancementBonuses = scaledBonuses, scrollTier = level, requiredLevel = level,
			usable = false, stackable = true, maxStack = 20, color = scrollColors[category],
		}
	end
end

for _, item in pairs(Items) do
	if item.slot and EquipmentSlots.DEFAULT_VISUAL_MODE[item.slot] then
		item.visualMode = item.visualMode or EquipmentSlots.DEFAULT_VISUAL_MODE[item.slot]
	end
end

return Items
