local LocalAnimationBuilder = require(script.Parent.Parent.Util.LocalAnimationBuilder)
local BalancingConfig = require(script.Parent.BalancingConfig)

local MonsterConfig = {
	Slime = {
		id = "Slime",
		name = "Slime",
		level = 1,
		maxHealth = 40,
		damage = 5,
		defense = 1,
		experienceReward = 20,
		goldReward = 10,
		lootTableId = "SlimeDrops",
		respawnTime = 5,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 12,
		attackCooldown = 4,
		aggroRange = 30,
		attackRange = 5,
		dropChance = 0.15, 
		dropItem = "Herb",
		color = Color3.fromRGB(50, 200, 100),
		damageType = "magic",
		passiveSkill = { statusEffect = "Slow", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.5,
	},
	Goblin = {
		id = "Goblin",
		name = "Goblin",
		level = 2,
		maxHealth = 100,
		damage = 10,
		defense = 3,
		experienceReward = 20,
		goldReward = 20,
		lootTableId = "GoblinDrops",
		respawnTime = 5,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 12,
		attackCooldown = 3,
		aggroRange = 40,
		attackRange = 6,
		dropChance = 0.15,
		dropItem = "Herb",
		color = Color3.fromRGB(60, 140, 60),
		damageType = "physical",
		passiveSkill = { statusEffect = "Bleed", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.4,
	},
	Spider = {
		id = "Spider",
		name = "Spider",
		level = 3,
		maxHealth = 150,
		damage = 15,
		defense = 2,
		experienceReward = 30,
		goldReward = 25,
		lootTableId = "SpiderDrops",
		respawnTime = 5,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 12, 
		attackCooldown = 2.5,
		aggroRange = 50,
		attackRange = 5,
		dropChance = 0.15,
		dropItem = "BeastHide",
		color = Color3.fromRGB(40, 40, 40),
		damageType = "magic",
		passiveSkill = { statusEffect = "Poison", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.35,
	},
	DireWolf = {
		id = "DireWolf",
		name = "Dire Wolf",
		level = 4,
		maxHealth = 200,
		damage = 20,
		defense = 4,
		experienceReward = 40,
		goldReward = 35,
		lootTableId = "WolfDrops",
		respawnTime = 6,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 12,
		attackCooldown = 2,
		aggroRange = 60,
		attackRange = 6,
		dropChance = 0.15,
		dropItem = "BeastHide",
		color = Color3.fromRGB(80, 80, 80),
		damageType = "physical",
		passiveSkill = { statusEffect = "Bleed", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.3,
	},
	Skeleton = {
		id = "Skeleton",
		name = "Skeleton",
		level = 5,
		maxHealth = 250,
		damage = 25,
		defense = 5,
		experienceReward = 50,
		goldReward = 30,
		lootTableId = "SkeletonDrops",
		respawnTime = 6,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 12, 
		attackCooldown = 3.5,
		aggroRange = 45,
		attackRange = 6,
		dropChance = 0.25,
		dropItem = "Herb",
		color = Color3.fromRGB(200, 200, 190),
		damageType = "physical",
		passiveSkill = { statusEffect = "Slow", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.45,
	},
	SkeletonKnight = {
		id = "SkeletonKnight",
		name = "Skeleton Knight",
		level = 6,
		maxHealth = 300,
		damage = 30,
		defense = 12,
		experienceReward = 60,
		goldReward = 80,
		lootTableId = "SkeletonDrops",
		respawnTime = 10,
		rarity = "Epic",
		mobType = "Hostile",
		moveSpeed = 12, 
		attackCooldown = 3,
		aggroRange = 45,
		attackRange = 7,
		dropChance = 0.4,
		dropItem = "IronOre",
		color = Color3.fromRGB(180, 180, 200),
		damageType = "physical",
		passiveSkill = { statusEffect = "Stun", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.45,
	},
	Orc = {
		id = "Orc",
		name = "Orc",
		level = 7,
		maxHealth = 350,
		damage = 35,
		defense = 8,
		experienceReward = 70,
		goldReward = 50,
		lootTableId = "OrcDrops",
		respawnTime = 8,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 12,
		attackCooldown = 4,
		aggroRange = 40,
		attackRange = 7,
		dropChance = 0.5,
		dropItem = "IronOre",
		color = Color3.fromRGB(50, 100, 40),
		damageType = "physical",
		passiveSkill = { statusEffect = "Stun", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.5,
	},
	Dragon = {
		id = "Dragon",
		name = "Dragon",
		level = 10,
		maxHealth = 1000,
		damage = 100,
		defense = 40,
		experienceReward = 500,
		goldReward = 500,
		lootTableId = "DragonDrops",
		respawnTime = 120,
		rarity = "Mythic",
		mobType = "Boss",
		moveSpeed = 12,
		attackCooldown = 5,
		aggroRange = 80,
		attackRange = 12,
		dropChance = 1.0,
		dropItem = "IronOre",
		color = Color3.fromRGB(180, 40, 40),
		damageType = "magic",
		isFlying = true,
		passiveSkill = { statusEffect = "Burn", procChance = 40, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.6,
	},
	Skorvath = {
		id = "Skorvath",
		name = "Skorvath, the Frostwing",
		level = 10,
		maxHealth = 1250,
		damage = 95,
		defense = 42,
		experienceReward = 500,
		goldReward = 500,
		lootTableId = "DragonDrops",
		respawnTime = 180,
		rarity = "Mythic",
		mobType = "Boss",
		moveSpeed = 12,
		attackCooldown = 5,
		aggroRange = 90,
		attackRange = 14,
		dropChance = 1.0,
		dropItem = "DragonHorn",
		color = Color3.fromRGB(150, 205, 255),
		damageType = "magic",
		isFlying = true,
		passiveSkill = { statusEffect = "Slow", procChance = 45, cooldown = 5 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.6,
	},
	Wyvern = {
		id = "Wyvern",
		name = "Wyvern",
		level = 8,
		maxHealth = 400,
		damage = 45,
		defense = 10,
		experienceReward = 80,
		goldReward = 60,
		lootTableId = "WyvernDrops",
		respawnTime = 10,
		rarity = "Epic",
		mobType = "Hostile",
		moveSpeed = 16,
		attackCooldown = 3,
		aggroRange = 60,
		attackRange = 8,
		dropChance = 0.5,
		dropItem = "IronOre",
		color = Color3.fromRGB(40, 100, 160),
		damageType = "magic",
		isFlying = true,
		passiveSkill = { statusEffect = "WindGust", procChance = 50, cooldown = 8 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.4,
	},
	Griffin = {
		id = "Griffin",
		name = "Griffin",
		level = 7,
		maxHealth = 350,
		damage = 40,
		defense = 12,
		experienceReward = 75,
		goldReward = 50,
		lootTableId = "GriffinDrops",
		respawnTime = 10,
		rarity = "Epic",
		mobType = "Hostile",
		moveSpeed = 15,
		attackCooldown = 3.5,
		aggroRange = 55,
		attackRange = 7,
		dropChance = 0.5,
		dropItem = "IronOre",
		color = Color3.fromRGB(220, 180, 50),
		damageType = "physical",
		isFlying = true,
		passiveSkill = { statusEffect = "Screech", procChance = 30, cooldown = 8 },
		walkAnimKey = "rbxassetid://507777826",
		idleAnimKey = "rbxassetid://507766388",
		attackAnimKeys = { "rbxassetid://507765000", "rbxassetid://507767968" },
		attackHitTime = 0.5,
	},
}

function MonsterConfig.GetAnimId(key)
	if type(key) == "string" and string.sub(key, 1, 13) == "rbxassetid://" then
		return key
	end
	return LocalAnimationBuilder.GetAnimId(key)
end

function MonsterConfig.ResolveExperienceReward(config)
	if config.experienceReward then
		return config.experienceReward
	end
	return BalancingConfig.CalculateMonsterExp(config.level or 1)
end

function MonsterConfig.ResolveGoldReward(config)
	return config.goldReward or config.coinReward or 0
end

function MonsterConfig.Normalize(config)
	if not config then
		return nil
	end

	return {
		id = config.id,
		name = config.name,
		level = config.level or 1,
		maxHealth = config.maxHealth or config.MaxHP or 50,
		damage = config.damage or config.PhysicalDamage or 5,
		defense = config.defense or config.PhysicalResistance or 0,
		experienceReward = MonsterConfig.ResolveExperienceReward(config),
		goldReward = MonsterConfig.ResolveGoldReward(config),
		coinReward = MonsterConfig.ResolveGoldReward(config),
		xpReward = MonsterConfig.ResolveExperienceReward(config),
		MaxHP = config.maxHealth or config.MaxHP or 50,
		PhysicalDamage = config.damage or config.PhysicalDamage or 5,
		PhysicalResistance = config.defense or config.PhysicalResistance or 0,
		lootTableId = config.lootTableId,
		respawnTime = config.respawnTime or 5,
		rarity = config.rarity or "Common",
		mobType = config.mobType or "Hostile",
		moveSpeed = config.moveSpeed or config.MoveSpeed or 4,
		isFlying = config.isFlying,
		attackCooldown = config.attackCooldown or 3,
		aggroRange = config.aggroRange or 40,
		attackRange = config.attackRange or 6,
		dropChance = config.dropChance or 0.25,
		dropItem = config.dropItem,
		color = config.color,
		damageType = config.damageType or "physical",
		statusEffect = config.statusEffect,
		passiveSkill = config.passiveSkill,
		walkAnimKey = config.walkAnimKey,
		idleAnimKey = config.idleAnimKey,
		attackAnimKeys = config.attackAnimKeys,
		attackHitTime = config.attackHitTime,
	}
end

function MonsterConfig.Get(enemyId)
	local config = MonsterConfig[enemyId]
	if not config then
		return nil
	end
	return MonsterConfig.Normalize(config)
end

return MonsterConfig




