local LocalAnimationBuilder = require(script.Parent.Parent.Util.LocalAnimationBuilder)
local BalancingConfig = require(script.Parent.BalancingConfig)

local MonsterConfig = {
	Slime = {
		id = "Slime",
		name = "Slime",
		level = 1,
		maxHealth = 40,
		damage = 5,
		defense = 1,
		experienceReward = 20,
		goldReward = 10,
		lootTableId = "SlimeDrops",
		respawnTime = 5,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 2,
		attackCooldown = 4,
		aggroRange = 30,
		attackRange = 5,
		dropChance = 0.2,
		dropItem = "Herb",
		color = Color3.fromRGB(50, 200, 100),
		damageType = "magic",
		statusEffect = "Slow",
		walkAnimKey = "GetSlimeWalk",
		idleAnimKey = "GetSlimeIdle",
		attackAnimKeys = { "GetSlimeAttack1", "GetSlimeAttack2" },
		attackHitTime = 0.5,
	},
	Goblin = {
		id = "Goblin",
		name = "Goblin",
		level = 5,
		maxHealth = 50,
		damage = 8,
		defense = 3,
		experienceReward = 80,
		goldReward = 20,
		lootTableId = "GoblinDrops",
		respawnTime = 5,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 4,
		attackCooldown = 3,
		aggroRange = 40,
		attackRange = 6,
		dropChance = 0.35,
		dropItem = "Herb",
		color = Color3.fromRGB(60, 140, 60),
		damageType = "physical",
		statusEffect = "Bleed",
		walkAnimKey = "GetGoblinWalk",
		idleAnimKey = "GetGoblinIdle",
		attackAnimKeys = { "GetGoblinAttack1", "GetGoblinAttack2" },
		attackHitTime = 0.4,
	},
	Spider = {
		id = "Spider",
		name = "Spider",
		level = 8,
		maxHealth = 60,
		damage = 10,
		defense = 2,
		experienceReward = 120,
		goldReward = 25,
		lootTableId = "SpiderDrops",
		respawnTime = 5,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 6,
		attackCooldown = 2.5,
		aggroRange = 50,
		attackRange = 5,
		dropChance = 0.4,
		dropItem = "BeastHide",
		color = Color3.fromRGB(40, 40, 40),
		damageType = "magic",
		statusEffect = "Poison",
		walkAnimKey = "GetSpiderWalk",
		idleAnimKey = "GetSpiderIdle",
		attackAnimKeys = { "GetSpiderAttack1", "GetSpiderAttack2" },
		attackHitTime = 0.35,
	},
	DireWolf = {
		id = "DireWolf",
		name = "Dire Wolf",
		level = 10,
		maxHealth = 80,
		damage = 14,
		defense = 4,
		experienceReward = 180,
		goldReward = 35,
		lootTableId = "WolfDrops",
		respawnTime = 6,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 7,
		attackCooldown = 2,
		aggroRange = 60,
		attackRange = 6,
		dropChance = 0.3,
		dropItem = "BeastHide",
		color = Color3.fromRGB(80, 80, 80),
		damageType = "physical",
		statusEffect = "Bleed",
		walkAnimKey = "GetDireWolfWalk",
		idleAnimKey = "GetDireWolfIdle",
		attackAnimKeys = { "GetDireWolfAttack1", "GetDireWolfAttack2" },
		attackHitTime = 0.3,
	},
	Skeleton = {
		id = "Skeleton",
		name = "Skeleton",
		level = 15,
		maxHealth = 75,
		damage = 12,
		defense = 5,
		experienceReward = 350,
		goldReward = 30,
		lootTableId = "SkeletonDrops",
		respawnTime = 6,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 4,
		attackCooldown = 3.5,
		aggroRange = 45,
		attackRange = 6,
		dropChance = 0.25,
		dropItem = "Herb",
		color = Color3.fromRGB(200, 200, 190),
		damageType = "physical",
		statusEffect = "Slow",
		walkAnimKey = "GetSkeletonWalk",
		idleAnimKey = "GetSkeletonIdle",
		attackAnimKeys = { "GetSkeletonAttack1", "GetSkeletonAttack2" },
		attackHitTime = 0.45,
	},
	SkeletonKnight = {
		id = "SkeletonKnight",
		name = "Skeleton Knight",
		level = 20,
		maxHealth = 200,
		damage = 22,
		defense = 12,
		experienceReward = 650,
		goldReward = 80,
		lootTableId = "SkeletonDrops",
		respawnTime = 10,
		rarity = "Elite",
		mobType = "Hostile",
		moveSpeed = 4,
		attackCooldown = 3,
		aggroRange = 45,
		attackRange = 7,
		dropChance = 0.4,
		dropItem = "IronOre",
		color = Color3.fromRGB(180, 180, 200),
		damageType = "physical",
		statusEffect = "Stun",
		walkAnimKey = "GetSkeletonWalk",
		idleAnimKey = "GetSkeletonIdle",
		attackAnimKeys = { "GetSkeletonAttack1", "GetSkeletonAttack2" },
		attackHitTime = 0.45,
	},
	Orc = {
		id = "Orc",
		name = "Orc",
		level = 25,
		maxHealth = 120,
		damage = 18,
		defense = 8,
		experienceReward = 900,
		goldReward = 50,
		lootTableId = "OrcDrops",
		respawnTime = 8,
		rarity = "Common",
		mobType = "Hostile",
		moveSpeed = 3,
		attackCooldown = 4,
		aggroRange = 40,
		attackRange = 7,
		dropChance = 0.5,
		dropItem = "IronOre",
		color = Color3.fromRGB(50, 100, 40),
		damageType = "physical",
		statusEffect = "Stun",
		walkAnimKey = "GetOrcWalk",
		idleAnimKey = "GetOrcIdle",
		attackAnimKeys = { "GetOrcAttack1", "GetOrcAttack2", "GetOrcAttack3" },
		attackHitTime = 0.5,
	},
	Dragon = {
		id = "Dragon",
		name = "Dragon",
		level = 60,
		maxHealth = 5000,
		damage = 80,
		defense = 40,
		experienceReward = 8000,
		goldReward = 500,
		lootTableId = "OrcDrops",
		respawnTime = 120,
		rarity = "Boss",
		mobType = "Boss",
		moveSpeed = 5,
		attackCooldown = 5,
		aggroRange = 80,
		attackRange = 12,
		dropChance = 1.0,
		dropItem = "IronOre",
		color = Color3.fromRGB(180, 40, 40),
		damageType = "magic",
		statusEffect = "Burn",
		walkAnimKey = "GetOrcWalk",
		idleAnimKey = "GetOrcIdle",
		attackAnimKeys = { "GetOrcAttack1", "GetOrcAttack2", "GetOrcAttack3" },
		attackHitTime = 0.6,
	},
}

function MonsterConfig.GetAnimId(key)
	return LocalAnimationBuilder.GetAnimId(key)
end

function MonsterConfig.ResolveExperienceReward(config)
	if config.experienceReward then
		return config.experienceReward
	end
	return BalancingConfig.CalculateMonsterExp(config.level or 1)
end

function MonsterConfig.ResolveGoldReward(config)
	return config.goldReward or config.coinReward or 0
end

function MonsterConfig.Normalize(config)
	if not config then
		return nil
	end

	return {
		id = config.id,
		name = config.name,
		level = config.level or 1,
		maxHealth = config.maxHealth or config.MaxHP or 50,
		damage = config.damage or config.PhysicalDamage or 5,
		defense = config.defense or config.PhysicalResistance or 0,
		experienceReward = MonsterConfig.ResolveExperienceReward(config),
		goldReward = MonsterConfig.ResolveGoldReward(config),
		coinReward = MonsterConfig.ResolveGoldReward(config),
		xpReward = MonsterConfig.ResolveExperienceReward(config),
		MaxHP = config.maxHealth or config.MaxHP or 50,
		PhysicalDamage = config.damage or config.PhysicalDamage or 5,
		PhysicalResistance = config.defense or config.PhysicalResistance or 0,
		lootTableId = config.lootTableId,
		respawnTime = config.respawnTime or 5,
		rarity = config.rarity or "Common",
		mobType = config.mobType or "Hostile",
		moveSpeed = config.moveSpeed or config.MoveSpeed or 4,
		attackCooldown = config.attackCooldown or 3,
		aggroRange = config.aggroRange or 40,
		attackRange = config.attackRange or 6,
		dropChance = config.dropChance or 0.25,
		dropItem = config.dropItem,
		color = config.color,
		damageType = config.damageType or "physical",
		statusEffect = config.statusEffect,
		walkAnimKey = config.walkAnimKey,
		idleAnimKey = config.idleAnimKey,
		attackAnimKeys = config.attackAnimKeys,
		attackHitTime = config.attackHitTime,
	}
end

function MonsterConfig.Get(enemyId)
	local config = MonsterConfig[enemyId]
	if not config then
		return nil
	end
	return MonsterConfig.Normalize(config)
end

return MonsterConfig
