-- ⚠️ ANIMATION IDs ARE PLACEHOLDERS — Replace each rbxassetid://9XXXXXXX with your actual uploaded animation ID.
-- Warrior auto-attack combo: 90000001–90000005 | skill casts: 90000006–90000009
-- Mage    auto-attack combo: 90000011–90000015 | skill casts: 90000016–90000019 | projectile: 90000010
-- Archer  auto-attack combo: 90000021–90000025 | skill casts: 90000026–90000029 | projectile: 90000020
-- Priest  auto-attack combo: 90000031–90000035 | skill casts: 90000036–90000039
-- Kavalier auto-attack combo: 90000041–90000045 | skill casts: 90000046–90000049 | projectile: 90000040
-- Player walk/idle: 90000051–90000060

local Skills = {
	Warrior_AutoAttack = {
		id = "Warrior_AutoAttack",
		name = "Auto Attack",
		description = "A basic melee strike.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 0,
		healAmount = 0,
		range = 10,
		skillType = "melee",
		comboAnims = {
			"rbxassetid://4524724749",
			"rbxassetid://4524724749",
			"rbxassetid://4524724749",
			"rbxassetid://4524724749",
			"rbxassetid://4524724749",
		},
		comboAdvance = "sequential",
		castTime = 0.3,
		hitAnimMarker = "Hit",
	},
	Warrior_Slash = {
		id = "Warrior_Slash",
		name = "Slash",
		description = "A powerful horizontal slash.",
		cooldown = 4,
		manaCost = 8,
		damage = 25,
		range = 10,
		skillType = "melee",
		castAnimId = "rbxassetid://90000006",
		castTime = 0.5,
		hitAnimMarker = "Hit",
	},
	Warrior_Charge = {
		id = "Warrior_Charge",
		name = "Charge",
		description = "Rush forward and strike the enemy.",
		cooldown = 8,
		manaCost = 12,
		damage = 35,
		range = 14,
		skillType = "melee",
		castAnimId = "rbxassetid://90000007",
		castTime = 0.6,
		hitAnimMarker = "Hit",
	},
	Warrior_Whirlwind = {
		id = "Warrior_Whirlwind",
		name = "Whirlwind",
		description = "Spin and damage all nearby enemies.",
		cooldown = 12,
		manaCost = 18,
		damage = 20,
		range = 8,
		skillType = "melee",
		aoe = true,
		castAnimId = "rbxassetid://90000008",
		castTime = 0.7,
		hitAnimMarker = "Hit",
	},
	Warrior_Berserk = {
		id = "Warrior_Berserk",
		name = "Berserk",
		description = "Enter a rage, greatly increasing attack power.",
		cooldown = 30,
		manaCost = 25,
		damage = 50,
		range = 10,
		skillType = "melee",
		castAnimId = "rbxassetid://90000009",
		castTime = 1.0,
		hitAnimMarker = "Hit",
	},
	Mage_AutoAttack = {
		id = "Mage_AutoAttack",
		name = "Magic Bolt",
		description = "Fire a bolt of arcane energy.",
		slotType = "autoAttack",
		cooldown = 0.8,
		manaCost = 0,
		damage = 8,
		range = 40,
		skillType = "magic",
		comboAnims = {
			"rbxassetid://90000011",
			"rbxassetid://90000012",
			"rbxassetid://90000013",
			"rbxassetid://90000014",
			"rbxassetid://90000015",
		},
		comboAdvance = "sequential",
		castTime = 0.4,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 80,
	},
	Mage_Fireball = {
		id = "Mage_Fireball",
		name = "Fireball",
		description = "Hurl a ball of fire at the target.",
		cooldown = 5,
		manaCost = 15,
		damage = 30,
		range = 45,
		skillType = "magic",
		castAnimId = "rbxassetid://90000016",
		castTime = 0.6,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 60,
	},
	Mage_IceSpike = {
		id = "Mage_IceSpike",
		name = "Ice Spike",
		description = "Summon a spike of ice from the ground.",
		cooldown = 7,
		manaCost = 18,
		damage = 28,
		range = 40,
		skillType = "magic",
		castAnimId = "rbxassetid://90000017",
		castTime = 0.7,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 70,
	},
	Mage_LightningStorm = {
		id = "Mage_LightningStorm",
		name = "Lightning Storm",
		description = "Call down lightning on nearby enemies.",
		cooldown = 14,
		manaCost = 25,
		damage = 22,
		range = 30,
		skillType = "magic",
		aoe = true,
		castAnimId = "rbxassetid://90000018",
		castTime = 0.8,
	},
	Mage_Meteor = {
		id = "Mage_Meteor",
		name = "Meteor",
		description = "Summon a devastating meteor from the sky.",
		cooldown = 35,
		manaCost = 40,
		damage = 80,
		range = 50,
		skillType = "magic",
		castAnimId = "rbxassetid://90000019",
		castTime = 1.2,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 40,
	},
	Archer_AutoAttack = {
		id = "Archer_AutoAttack",
		name = "Arrow Shot",
		description = "Fire a single arrow.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 10,
		range = 50,
		skillType = "ranged",
		comboAnims = {
			"rbxassetid://90000021",
			"rbxassetid://90000022",
			"rbxassetid://90000023",
			"rbxassetid://90000024",
			"rbxassetid://90000025",
		},
		comboAdvance = "sequential",
		castTime = 0.3,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 120,
	},
	Archer_MultiShot = {
		id = "Archer_MultiShot",
		name = "Multi Shot",
		description = "Fire multiple arrows at once.",
		cooldown = 6,
		manaCost = 12,
		damage = 18,
		range = 45,
		skillType = "ranged",
		castAnimId = "rbxassetid://90000026",
		castTime = 0.5,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 100,
	},
	Archer_PiercingArrow = {
		id = "Archer_PiercingArrow",
		name = "Piercing Arrow",
		description = "An arrow that pierces through enemies.",
		cooldown = 8,
		manaCost = 15,
		damage = 32,
		range = 55,
		skillType = "ranged",
		castAnimId = "rbxassetid://90000027",
		castTime = 0.6,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 150,
	},
	Archer_RainOfArrows = {
		id = "Archer_RainOfArrows",
		name = "Rain of Arrows",
		description = "Shower an area with arrows.",
		cooldown = 14,
		manaCost = 22,
		damage = 20,
		range = 40,
		skillType = "ranged",
		aoe = true,
		castAnimId = "rbxassetid://90000028",
		castTime = 0.8,
	},
	Archer_SniperShot = {
		id = "Archer_SniperShot",
		name = "Sniper Shot",
		description = "A precise shot that deals massive damage.",
		cooldown = 30,
		manaCost = 30,
		damage = 90,
		range = 80,
		skillType = "ranged",
		castAnimId = "rbxassetid://90000029",
		castTime = 1.0,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 200,
	},
	Priest_AutoAttack = {
		id = "Priest_AutoAttack",
		name = "Holy Attack",
		description = "Strike with holy light.",
		slotType = "autoAttack",
		cooldown = 0.8,
		manaCost = 0,
		damage = 8,
		range = 12,
		skillType = "magic",
		comboAnims = {
			"rbxassetid://90000031",
			"rbxassetid://90000032",
			"rbxassetid://90000033",
			"rbxassetid://90000034",
			"rbxassetid://90000035",
		},
		comboAdvance = "sequential",
		castTime = 0.4,
		hitAnimMarker = "Hit",
	},
	Priest_Heal = {
		id = "Priest_Heal",
		name = "Heal",
		description = "Restore health to yourself and nearby party members.",
		cooldown = 6,
		manaCost = 15,
		healAmount = 40,
		range = 20,
		skillType = "heal",
		castAnimId = "rbxassetid://90000036",
		castTime = 0.5,
	},
	Priest_Blessing = {
		id = "Priest_Blessing",
		name = "Blessing",
		description = "Bless yourself and nearby party members, increasing defense.",
		cooldown = 12,
		manaCost = 18,
		range = 20,
		skillType = "buff",
		statusEffect = "Blessing",
		statusDuration = 8,
		buffStats = { defense = 8 },
		castAnimId = "rbxassetid://90000037",
		castTime = 0.6,
	},
	Priest_HolyNova = {
		id = "Priest_HolyNova",
		name = "Holy Nova",
		description = "Burst of holy energy damaging nearby enemies.",
		cooldown = 10,
		manaCost = 20,
		damage = 25,
		range = 12,
		skillType = "magic",
		aoe = true,
		castAnimId = "rbxassetid://90000038",
		castTime = 0.6,
		hitAnimMarker = "Hit",
	},
	Priest_DivineProtection = {
		id = "Priest_DivineProtection",
		name = "Divine Protection",
		description = "Shield yourself and nearby party members with divine power.",
		cooldown = 35,
		manaCost = 35,
		shieldAmount = 60,
		range = 20,
		skillType = "buff",
		statusEffect = "DivineShield",
		statusDuration = 10,
		castAnimId = "rbxassetid://90000039",
		castTime = 0.8,
	},
	Kavalier_AutoAttack = {
		id = "Kavalier_AutoAttack",
		name = "Spear Thrust",
		description = "Thrust your spear forward.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 12,
		range = 12,
		skillType = "melee",
		comboAnims = {
			"rbxassetid://4524724749",
			"rbxassetid://90000042",
			"rbxassetid://90000043",
			"rbxassetid://90000044",
			"rbxassetid://90000045",
		},
		comboAdvance = "sequential",
		castTime = 0.3,
		hitAnimMarker = "Hit",
	},
	Kavalier_DashStrike = {
		id = "Kavalier_DashStrike",
		name = "Dash Strike",
		description = "Dash forward and impale the enemy.",
		cooldown = 7,
		manaCost = 14,
		damage = 38,
		range = 16,
		skillType = "melee",
		castAnimId = "rbxassetid://90000046",
		castTime = 0.5,
		hitAnimMarker = "Hit",
	},
	Kavalier_SpearThrow = {
		id = "Kavalier_SpearThrow",
		name = "Spear Throw",
		description = "Throw your spear at a distant target.",
		cooldown = 9,
		manaCost = 16,
		damage = 30,
		range = 45,
		skillType = "ranged",
		castAnimId = "rbxassetid://90000047",
		castTime = 0.6,
		projectileId = "rbxassetid://90000040",
		projectileSpeed = 90,
	},
	Kavalier_LanceSpin = {
		id = "Kavalier_LanceSpin",
		name = "Lance Spin",
		description = "Spin your lance, damaging all around you.",
		cooldown = 12,
		manaCost = 20,
		damage = 22,
		range = 10,
		skillType = "melee",
		aoe = true,
		castAnimId = "rbxassetid://90000048",
		castTime = 0.7,
		hitAnimMarker = "Hit",
	},
	Kavalier_DragonCharge = {
		id = "Kavalier_DragonCharge",
		name = "Dragon Charge",
		description = "Charge like a dragon, devastating all in your path.",
		cooldown = 32,
		manaCost = 28,
		damage = 65,
		range = 20,
		skillType = "melee",
		castAnimId = "rbxassetid://90000049",
		castTime = 1.0,
		hitAnimMarker = "Hit",
	},
}

return Skills
