-- ⚠️ ANIMATION IDs ARE PLACEHOLDERS — Replace each rbxassetid://9XXXXXXX with your actual uploaded animation ID.
-- Warrior auto-attack combo: 90000001–90000005 | skill casts: 90000006–90000009
-- Mage    auto-attack combo: 90000011–90000015 | skill casts: 90000016–90000019 | projectile: 90000010
-- Archer  auto-attack combo: 90000021–90000025 | skill casts: 90000026–90000029 | projectile: 90000020
-- Priest  auto-attack combo: 90000031–90000035 | skill casts: 90000036–90000039
-- Kavalier auto-attack combo: 90000041–90000045 | skill casts: 90000046–90000049 | projectile: 90000040
-- Player walk/idle: 90000051–90000060

local LocalAnimationBuilder = require(script.Parent.Parent.Util.LocalAnimationBuilder)

local Skills = {
	Warrior_AutoAttack = {
		id = "Warrior_AutoAttack",
		requiredMasteryRank = 1,
		name = "Auto Attack",
		description = "A basic melee strike.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 0,
		healAmount = 0,
		range = 10,
		skillType = "melee",
		comboAnims = {
			"rbxassetid://140580133625859",
			"rbxassetid://96088875892368",
			"rbxassetid://100801918271328",
		},
		comboAdvance = "sequential",
		castTime = 0.7,
		hitAnimMarker = "Hit",
	},
	Warrior_Slash = {
		id = "Warrior_Slash",
		requiredMasteryRank = 1,
		name = "Slash",
		description = "A powerful horizontal slash.",
		cooldown = 4,
		manaCost = 8,
		damage = 25,
		range = 10,
		skillType = "melee",
		castAnimId = LocalAnimationBuilder.GetWarriorSlash(),
		castTime = 0.5,
		hitAnimMarker = "Hit",
	},
	Warrior_Charge = {
		id = "Warrior_Charge",
		requiredMasteryRank = 2,
		name = "Leap Strike",
		description = "Leap forward and strike the enemy.",
		cooldown = 8,
		manaCost = 12,
		damage = 35,
		range = 14,
		skillType = "melee",
		castAnimId = LocalAnimationBuilder.GetWarriorCharge(),
		castTime = 0.6,
		hitAnimMarker = "Hit",
	},
	Warrior_Whirlwind = {
		id = "Warrior_Whirlwind",
		requiredMasteryRank = 3,
		name = "Whirlwind",
		description = "Spin and damage all nearby enemies.",
		cooldown = 12,
		manaCost = 18,
		damage = 20,
		range = 8,
		skillType = "melee",
		aoe = true,
		castAnimId = LocalAnimationBuilder.GetWarriorWhirlwind(),
		castTime = 0.7,
		hitAnimMarker = "Hit",
	},
	Warrior_Berserk = {
		id = "Warrior_Berserk",
		requiredMasteryRank = 4,
		name = "Berserk",
		description = "Enter a rage, greatly increasing attack power.",
		cooldown = 30,
		manaCost = 25,
		damage = 50,
		range = 10,
		skillType = "melee",
		castAnimId = LocalAnimationBuilder.GetWarriorBerserk(),
		castTime = 1.0,
		hitAnimMarker = "Hit",
	},
	Mage_AutoAttack = {
		id = "Mage_AutoAttack",
		requiredMasteryRank = 1,
		name = "Magic Bolt",
		description = "Fire a bolt of arcane energy.",
		slotType = "autoAttack",
		cooldown = 0.8,
		manaCost = 0,
		damage = 8,
		range = 40,
		skillType = "magic",
		comboAnims = {
			LocalAnimationBuilder.GetMageAuto1(),
			LocalAnimationBuilder.GetMageAuto2(),
			LocalAnimationBuilder.GetMageAuto3(),
			LocalAnimationBuilder.GetMageAuto4(),
			LocalAnimationBuilder.GetMageAuto5(),
		},
		comboAdvance = "sequential",
		castTime = 0.8,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 80,
	},
	Mage_Fireball = {
		id = "Mage_Fireball",
		requiredMasteryRank = 1,
		name = "Fireball",
		description = "Hurl a ball of fire at the target.",
		cooldown = 5,
		manaCost = 15,
		damage = 30,
		range = 45,
		skillType = "magic",
		castAnimId = LocalAnimationBuilder.GetMageFireball(),
		castTime = 0.6,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 60,
	},
	Mage_IceSpike = {
		id = "Mage_IceSpike",
		requiredMasteryRank = 2,
		name = "Ice Spike",
		description = "Summon a spike of ice from the ground.",
		cooldown = 7,
		manaCost = 18,
		damage = 28,
		range = 40,
		skillType = "magic",
		castAnimId = LocalAnimationBuilder.GetMageIceSpike(),
		castTime = 0.7,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 70,
	},
	Mage_LightningStorm = {
		id = "Mage_LightningStorm",
		requiredMasteryRank = 3,
		name = "Staff Lightning",
		description = "Call down lightning on nearby enemies.",
		cooldown = 14,
		manaCost = 25,
		damage = 22,
		range = 30,
		skillType = "magic",
		aoe = true,
		castAnimId = LocalAnimationBuilder.GetMageLightningStorm(),
		castTime = 0.8,
	},
	Mage_Meteor = {
		id = "Mage_Meteor",
		requiredMasteryRank = 4,
		name = "Meteor",
		description = "Summon a devastating meteor from the sky.",
		cooldown = 35,
		manaCost = 40,
		damage = 80,
		range = 50,
		skillType = "magic",
		castAnimId = LocalAnimationBuilder.GetMageMeteor(),
		castTime = 1.2,
		projectileId = "rbxassetid://90000010",
		projectileSpeed = 40,
	},
	Archer_AutoAttack = {
		id = "Archer_AutoAttack",
		requiredMasteryRank = 1,
		name = "Arrow Shot",
		description = "Fire a single arrow.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 10,
		range = 50,
		skillType = "ranged",
		comboAnims = {
			"rbxassetid://132654410424890",
		},
		comboAdvance = "sequential",
		castTime = 0.7,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 120,
		arrowColor = Color3.fromRGB(200, 120, 50),
		pierceCount = 0,
	},
	Archer_MultiShot = {
		id = "Archer_MultiShot",
		requiredMasteryRank = 1,
		name = "Multi Shot",
		description = "Fire multiple arrows at once.",
		cooldown = 6,
		manaCost = 12,
		damage = 18,
		range = 45,
		skillType = "ranged",
		castAnimId = LocalAnimationBuilder.GetArcherMultiShot(),
		castTime = 0.5,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 100,
		arrowColor = Color3.fromRGB(180, 100, 255),
		pierceCount = 0,
	},
	Archer_PiercingArrow = {
		id = "Archer_PiercingArrow",
		requiredMasteryRank = 2,
		name = "Piercing Arrow",
		description = "An arrow that pierces through enemies.",
		cooldown = 8,
		manaCost = 15,
		damage = 32,
		range = 55,
		skillType = "ranged",
		castAnimId = LocalAnimationBuilder.GetArcherPiercingArrow(),
		castTime = 0.6,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 150,
		arrowColor = Color3.fromRGB(80, 200, 255),
		pierceCount = 3,
	},
	Archer_RainOfArrows = {
		id = "Archer_RainOfArrows",
		requiredMasteryRank = 3,
		name = "Rain of Arrows",
		description = "Shower an area with arrows.",
		cooldown = 14,
		manaCost = 22,
		damage = 20,
		range = 40,
		skillType = "ranged",
		aoe = true,
		castAnimId = LocalAnimationBuilder.GetArcherRainOfArrows(),
		castTime = 0.8,
	},
	Archer_SniperShot = {
		id = "Archer_SniperShot",
		requiredMasteryRank = 4,
		name = "Long Shot",
		description = "A precise shot that deals massive damage.",
		cooldown = 30,
		manaCost = 30,
		damage = 90,
		range = 80,
		skillType = "ranged",
		castAnimId = LocalAnimationBuilder.GetArcherSniperShot(),
		castTime = 1.0,
		projectileId = "rbxassetid://90000020",
		projectileSpeed = 200,
		arrowColor = Color3.fromRGB(255, 200, 50),
		pierceCount = 1,
	},
	Priest_AutoAttack = {
		id = "Priest_AutoAttack",
		requiredMasteryRank = 1,
		name = "Holy Attack",
		description = "Strike with holy light.",
		slotType = "autoAttack",
		cooldown = 0.8,
		manaCost = 0,
		damage = 8,
		range = 12,
		skillType = "magic",
		coneAngle = 160,
		comboAnims = {
			"rbxassetid://140580133625859",
			"rbxassetid://96088875892368",
			"rbxassetid://100801918271328",
		},
		comboAdvance = "sequential",
		castTime = 0.8,
		hitAnimMarker = "Hit",
	},
	Priest_Heal = {
		id = "Priest_Heal",
		requiredMasteryRank = 1,
		name = "Heal",
		description = "Restore health to yourself and nearby party members.",
		cooldown = 6,
		manaCost = 15,
		healAmount = 40,
		range = 20,
		skillType = "heal",
		castAnimId = LocalAnimationBuilder.GetPriestHeal(),
		castTime = 0.5,
	},
	Priest_Blessing = {
		id = "Priest_Blessing",
		requiredMasteryRank = 2,
		name = "Blessing",
		description = "Bless yourself and nearby party members, increasing defense.",
		cooldown = 12,
		manaCost = 18,
		range = 20,
		skillType = "buff",
		statusEffect = "Blessing",
		statusDuration = 8,
		buffStats = { defense = 8 },
		castAnimId = LocalAnimationBuilder.GetPriestBlessing(),
		castTime = 0.6,
	},
	Priest_HolyNova = {
		id = "Priest_HolyNova",
		requiredMasteryRank = 3,
		name = "Holy Nova",
		description = "Burst of holy energy damaging nearby enemies.",
		cooldown = 10,
		manaCost = 20,
		damage = 25,
		range = 12,
		skillType = "magic",
		coneAngle = 160,
		aoe = true,
		castAnimId = LocalAnimationBuilder.GetPriestHolyNova(),
		castTime = 0.6,
		hitAnimMarker = "Hit",
	},
	Priest_DivineProtection = {
		id = "Priest_DivineProtection",
		requiredMasteryRank = 4,
		name = "Divine Protection",
		description = "Shield yourself and nearby party members with divine power.",
		cooldown = 35,
		manaCost = 35,
		shieldAmount = 60,
		range = 20,
		skillType = "buff",
		statusEffect = "DivineShield",
		statusDuration = 10,
		castAnimId = LocalAnimationBuilder.GetPriestDivineProtection(),
		castTime = 0.8,
	},
	Kavalier_AutoAttack = {
		id = "Kavalier_AutoAttack",
		requiredMasteryRank = 1,
		name = "Spear Thrust",
		description = "Thrust your spear forward.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 12,
		range = 16,
		skillType = "melee",
		coneAngle = 160,
		comboAnims = {
			"rbxassetid://140580133625859",
			"rbxassetid://96088875892368",
			"rbxassetid://100801918271328",
		},
		comboAdvance = "sequential",
		castTime = 0.7,
		hitAnimMarker = "Hit",
	},
	Kavalier_DashStrike = {
		id = "Kavalier_DashStrike",
		requiredMasteryRank = 1,
		name = "Dash Strike",
		description = "Dash forward and impale the enemy.",
		cooldown = 7,
		manaCost = 14,
		damage = 38,
		range = 20,
		skillType = "melee",
		coneAngle = 160,
		castAnimId = LocalAnimationBuilder.GetKavalierDashStrike(),
		castTime = 0.5,
		hitAnimMarker = "Hit",
	},
	Kavalier_SpearThrow = {
		id = "Kavalier_SpearThrow",
		requiredMasteryRank = 2,
		name = "Spear Throw",
		description = "Throw your spear at a distant target.",
		cooldown = 9,
		manaCost = 16,
		damage = 30,
		range = 45,
		skillType = "ranged",
		castAnimId = LocalAnimationBuilder.GetKavalierSpearThrow(),
		castTime = 0.6,
		projectileId = "rbxassetid://90000040",
		projectileSpeed = 90,
	},
	Kavalier_LanceSpin = {
		id = "Kavalier_LanceSpin",
		requiredMasteryRank = 3,
		name = "Lance Spin",
		description = "Spin your lance, damaging all around you.",
		cooldown = 12,
		manaCost = 20,
		damage = 22,
		range = 14,
		skillType = "melee",
		coneAngle = 160,
		aoe = true,
		castAnimId = LocalAnimationBuilder.GetKavalierLanceSpin(),
		castTime = 0.7,
		hitAnimMarker = "Hit",
	},
	Kavalier_DragonCharge = {
		id = "Kavalier_DragonCharge",
		requiredMasteryRank = 4,
		name = "Dragon Charge",
		description = "Charge like a dragon, devastating all in your path.",
		cooldown = 32,
		manaCost = 28,
		damage = 65,
		range = 24,
		skillType = "melee",
		coneAngle = 160,
		castAnimId = LocalAnimationBuilder.GetKavalierDragonCharge(),
		castTime = 1.0,
		hitAnimMarker = "Hit",
	},
}

local SkillConfig = require(script.Parent.SkillConfig)

local TARGETING_OVERRIDES = {
	Warrior_Whirlwind = { targetType = "circle", aoeRadius = 8, showAoeIndicator = true },
	Mage_IceSpike = { targetType = "single", aoeRadius = 15, showAoeIndicator = true },
	Mage_LightningStorm = { targetType = "circle", aoeRadius = 30, showAoeIndicator = true },
	Mage_Meteor = { targetType = "single", aoeRadius = 12, showAoeIndicator = true },
	Archer_RainOfArrows = { targetType = "single", aoeRadius = 10, showAoeIndicator = true },
	Priest_Heal = { targetType = "party_circle", aoeRadius = 20 },
	Priest_Blessing = { targetType = "party_circle", aoeRadius = 20 },
	Priest_HolyNova = { targetType = "circle", aoeRadius = 12, showAoeIndicator = true },
	Priest_DivineProtection = { targetType = "party_circle", aoeRadius = 20 },
	Kavalier_LanceSpin = { targetType = "circle", aoeRadius = 10, showAoeIndicator = true },
}

for skillId, overrides in TARGETING_OVERRIDES do
	local skill = Skills[skillId]
	if skill then
		for key, value in overrides do
			skill[key] = value
		end
	end
end

function Skills.Get(skillId)
	local skill = Skills[skillId]
	if not skill then
		return nil
	end
	return SkillConfig.Resolve(skill)
end

return Skills
