local Skills = {
	Warrior_AutoAttack = {
		id = "Warrior_AutoAttack",
		name = "Auto Attack",
		description = "A basic melee strike.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 0,
		healAmount = 0,
		range = 10,
		skillType = "melee",
	},
	Warrior_Slash = {
		id = "Warrior_Slash",
		name = "Slash",
		description = "A powerful horizontal slash.",
		cooldown = 4,
		manaCost = 8,
		damage = 25,
		range = 10,
		skillType = "melee",
	},
	Warrior_Charge = {
		id = "Warrior_Charge",
		name = "Charge",
		description = "Rush forward and strike the enemy.",
		cooldown = 8,
		manaCost = 12,
		damage = 35,
		range = 14,
		skillType = "melee",
	},
	Warrior_Whirlwind = {
		id = "Warrior_Whirlwind",
		name = "Whirlwind",
		description = "Spin and damage all nearby enemies.",
		cooldown = 12,
		manaCost = 18,
		damage = 20,
		range = 8,
		skillType = "melee",
		aoe = true,
	},
	Warrior_Berserk = {
		id = "Warrior_Berserk",
		name = "Berserk",
		description = "Enter a rage, greatly increasing attack power.",
		cooldown = 30,
		manaCost = 25,
		damage = 50,
		range = 10,
		skillType = "melee",
	},
	Mage_AutoAttack = {
		id = "Mage_AutoAttack",
		name = "Magic Bolt",
		description = "Fire a bolt of arcane energy.",
		slotType = "autoAttack",
		cooldown = 0.8,
		manaCost = 0,
		damage = 8,
		range = 40,
		skillType = "magic",
	},
	Mage_Fireball = {
		id = "Mage_Fireball",
		name = "Fireball",
		description = "Hurl a ball of fire at the target.",
		cooldown = 5,
		manaCost = 15,
		damage = 30,
		range = 45,
		skillType = "magic",
	},
	Mage_IceSpike = {
		id = "Mage_IceSpike",
		name = "Ice Spike",
		description = "Summon a spike of ice from the ground.",
		cooldown = 7,
		manaCost = 18,
		damage = 28,
		range = 40,
		skillType = "magic",
	},
	Mage_LightningStorm = {
		id = "Mage_LightningStorm",
		name = "Lightning Storm",
		description = "Call down lightning on nearby enemies.",
		cooldown = 14,
		manaCost = 25,
		damage = 22,
		range = 30,
		skillType = "magic",
		aoe = true,
	},
		Mage_Meteor = {
		id = "Mage_Meteor",
		name = "Meteor",
		description = "Summon a devastating meteor from the sky.",
		cooldown = 35,
		manaCost = 40,
		damage = 80,
		range = 50,
		skillType = "magic",
	},
	Archer_AutoAttack = {
		id = "Archer_AutoAttack",
		name = "Arrow Shot",
		description = "Fire a single arrow.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 10,
		range = 50,
		skillType = "ranged",
	},
	Archer_MultiShot = {
		id = "Archer_MultiShot",
		name = "Multi Shot",
		description = "Fire multiple arrows at once.",
		cooldown = 6,
		manaCost = 12,
		damage = 18,
		range = 45,
		skillType = "ranged",
	},
	Archer_PiercingArrow = {
		id = "Archer_PiercingArrow",
		name = "Piercing Arrow",
		description = "An arrow that pierces through enemies.",
		cooldown = 8,
		manaCost = 15,
		damage = 32,
		range = 55,
		skillType = "ranged",
	},
	Archer_RainOfArrows = {
		id = "Archer_RainOfArrows",
		name = "Rain of Arrows",
		description = "Shower an area with arrows.",
		cooldown = 14,
		manaCost = 22,
		damage = 20,
		range = 40,
		skillType = "ranged",
		aoe = true,
	},
		Archer_SniperShot = {
		id = "Archer_SniperShot",
		name = "Sniper Shot",
		description = "A precise shot that deals massive damage.",
		cooldown = 30,
		manaCost = 30,
		damage = 90,
		range = 80,
		skillType = "ranged",
	},
	Priest_AutoAttack = {
		id = "Priest_AutoAttack",
		name = "Holy Attack",
		description = "Strike with holy light.",
		slotType = "autoAttack",
		cooldown = 0.8,
		manaCost = 0,
		damage = 8,
		range = 12,
		skillType = "magic",
	},
	Priest_Heal = {
		id = "Priest_Heal",
		name = "Heal",
		description = "Restore health to yourself and nearby party members.",
		cooldown = 6,
		manaCost = 15,
		healAmount = 40,
		range = 20,
		skillType = "heal",
	},
	Priest_Blessing = {
		id = "Priest_Blessing",
		name = "Blessing",
		description = "Bless yourself and nearby party members, increasing defense.",
		cooldown = 12,
		manaCost = 18,
		range = 20,
		skillType = "buff",
		statusEffect = "Blessing",
		statusDuration = 8,
		buffStats = { defense = 8 },
	},
	Priest_HolyNova = {
		id = "Priest_HolyNova",
		name = "Holy Nova",
		description = "Burst of holy energy damaging nearby enemies.",
		cooldown = 10,
		manaCost = 20,
		damage = 25,
		range = 12,
		skillType = "magic",
		aoe = true,
	},
		Priest_DivineProtection = {
		id = "Priest_DivineProtection",
		name = "Divine Protection",
		description = "Shield yourself and nearby party members with divine power.",
		cooldown = 35,
		manaCost = 35,
		shieldAmount = 60,
		range = 20,
		skillType = "buff",
		statusEffect = "DivineShield",
		statusDuration = 10,
	},
	Kavalier_AutoAttack = {
		id = "Kavalier_AutoAttack",
		name = "Spear Thrust",
		description = "Thrust your spear forward.",
		slotType = "autoAttack",
		cooldown = 0.7,
		manaCost = 0,
		damage = 12,
		range = 12,
		skillType = "melee",
	},
	Kavalier_DashStrike = {
		id = "Kavalier_DashStrike",
		name = "Dash Strike",
		description = "Dash forward and impale the enemy.",
		cooldown = 7,
		manaCost = 14,
		damage = 38,
		range = 16,
		skillType = "melee",
	},
	Kavalier_SpearThrow = {
		id = "Kavalier_SpearThrow",
		name = "Spear Throw",
		description = "Throw your spear at a distant target.",
		cooldown = 9,
		manaCost = 16,
		damage = 30,
		range = 45,
		skillType = "ranged",
	},
	Kavalier_LanceSpin = {
		id = "Kavalier_LanceSpin",
		name = "Lance Spin",
		description = "Spin your lance, damaging all around you.",
		cooldown = 12,
		manaCost = 20,
		damage = 22,
		range = 10,
		skillType = "melee",
		aoe = true,
	},
		Kavalier_DragonCharge = {
		id = "Kavalier_DragonCharge",
		name = "Dragon Charge",
		description = "Charge like a dragon, devastating all in your path.",
		cooldown = 32,
		manaCost = 28,
		damage = 65,
		range = 20,
		skillType = "melee",
	},
}

return Skills
